# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Building_Selection_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import main_control
import Reservationnew as CR
from view import gui as G


class Ui_BuildingSelection3(object):

    def logOut(self):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()

    def backButton(self):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()

    def setupUi(self, BuildingSelection3):
        BuildingSelection3.setObjectName("BuildingSelection3")
        BuildingSelection3.resize(1200, 600)
        BuildingSelection3.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(BuildingSelection3)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(660, 185, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.eligibleLabel = QtWidgets.QLabel(self.centralwidget)
        self.eligibleLabel.setGeometry(QtCore.QRect(970, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.eligibleLabel.setFont(font)
        self.eligibleLabel.setObjectName("eligibleLabel")
        self.genderLabel = QtWidgets.QLabel(self.centralwidget)
        self.genderLabel.setGeometry(QtCore.QRect(970, 180, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.ageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel.setGeometry(QtCore.QRect(660, 290, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.lastStayLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastStayLabel.setGeometry(QtCore.QRect(810, 380, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lastStayLabel.setFont(font)
        self.lastStayLabel.setObjectName("lastStayLabel")
        self.bookBedPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.bookBedPushButton.setGeometry(QtCore.QRect(700, 500, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.bookBedPushButton.setFont(font)
        self.bookBedPushButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.bookBedPushButton.setObjectName("bookBedPushButton")
        self.showNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel.setGeometry(QtCore.QRect(660, 240, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel.setFont(font)
        self.showNameLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showNameLabel.setObjectName("showNameLabel")
        self.showGenderLabel = QtWidgets.QLabel(self.centralwidget)
        self.showGenderLabel.setGeometry(QtCore.QRect(970, 240, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showGenderLabel.setFont(font)
        self.showGenderLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showGenderLabel.setObjectName("showGenderLabel")
        self.showAgeLabel = QtWidgets.QLabel(self.centralwidget)
        self.showAgeLabel.setGeometry(QtCore.QRect(660, 340, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showAgeLabel.setFont(font)
        self.showAgeLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showAgeLabel.setObjectName("showAgeLabel")
        self.showEligibleLabel = QtWidgets.QLabel(self.centralwidget)
        self.showEligibleLabel.setGeometry(QtCore.QRect(970, 350, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showEligibleLabel.setFont(font)
        self.showEligibleLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showEligibleLabel.setObjectName("showEligibleLabel")
        self.showLastStayLabel = QtWidgets.QLabel(self.centralwidget)
        self.showLastStayLabel.setGeometry(QtCore.QRect(740, 430, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showLastStayLabel.setFont(font)
        self.showLastStayLabel.setStyleSheet("text-align: center;\n"
"color: rgb(170, 0, 0);")
        self.showLastStayLabel.setObjectName("showLastStayLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(630, 160, 491, 321))
        self.label_2.setStyleSheet("image: url(:/newPrefix/C:/Users/lenovo/Desktop/4.jpg);\n"
"border-radius:10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 100, 651, 491))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 75, 132, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.buildingIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.buildingIdLabel.setGeometry(QtCore.QRect(100, 215, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buildingIdLabel.setFont(font)
        self.buildingIdLabel.setObjectName("buildingIdLabel")
        self.locationLabel = QtWidgets.QLabel(self.centralwidget)
        self.locationLabel.setGeometry(QtCore.QRect(100, 296, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.locationLabel.setFont(font)
        self.locationLabel.setObjectName("locationLabel")
        self.bedsAvaliableLabel = QtWidgets.QLabel(self.centralwidget)
        self.bedsAvaliableLabel.setGeometry(QtCore.QRect(100, 375, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bedsAvaliableLabel.setFont(font)
        self.bedsAvaliableLabel.setObjectName("bedsAvaliableLabel")
        self.showBuildingIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.showBuildingIdLabel.setGeometry(QtCore.QRect(100, 250, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showBuildingIdLabel.setFont(font)
        self.showBuildingIdLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showBuildingIdLabel.setObjectName("showBuildingIdLabel")
        self.showLocationLabel = QtWidgets.QLabel(self.centralwidget)
        self.showLocationLabel.setGeometry(QtCore.QRect(100, 330, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showLocationLabel.setFont(font)
        self.showLocationLabel.setStyleSheet("color: rgb(170, 0, 0);\n"
"text-align: left;")
        self.showLocationLabel.setObjectName("showLocationLabel")
        self.rightArrowToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.rightArrowToolButton.setGeometry(QtCore.QRect(310, 470, 41, 31))
        self.rightArrowToolButton.setStyleSheet("color: rgb(170, 0, 0);")
        self.rightArrowToolButton.setArrowType(QtCore.Qt.RightArrow)
        self.rightArrowToolButton.setObjectName("rightArrowToolButton")
        self.leftArrowToolButton = QtWidgets.QToolButton(self.centralwidget)
        self.leftArrowToolButton.setGeometry(QtCore.QRect(230, 470, 41, 31))
        self.leftArrowToolButton.setStyleSheet("color: rgb(170, 0, 0);")
        self.leftArrowToolButton.setArrowType(QtCore.Qt.LeftArrow)
        self.leftArrowToolButton.setObjectName("leftArrowToolButton")
        self.showBedAvaliableLabel = QtWidgets.QLabel(self.centralwidget)
        self.showBedAvaliableLabel.setGeometry(QtCore.QRect(100, 410, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showBedAvaliableLabel.setFont(font)
        self.showBedAvaliableLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showBedAvaliableLabel.setObjectName("showBedAvaliableLabel")
        self.homePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.homePushButton.setGeometry(QtCore.QRect(190, 520, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.homePushButton.setFont(font)
        self.homePushButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.homePushButton.setObjectName("homePushButton")
        self.backButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.backButton())
        self.backButton.setGeometry(QtCore.QRect(950, 20, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.adminDashboardLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel_2.setGeometry(QtCore.QRect(-10, 90, 531, 71))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel_2.setFont(font)
        self.adminDashboardLabel_2.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel_2.setObjectName("adminDashboardLabel_2")
        self.logOutButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.logOut())
        self.logOutButton.setGeometry(QtCore.QRect(1070, 20, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.logOutButton.setFont(font)
        self.logOutButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"

"image: url(logout (2).png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.logOutButton.setText("")
        self.logOutButton.setObjectName("logOutButton")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(10, 20, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setBold(False)
        font.setWeight(50)
        self.logoLabel.setFont(font)
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.label.raise_()
        self.bookBedPushButton.raise_()
        self.label_2.raise_()
        self.nameLabel.raise_()
        self.showNameLabel.raise_()
        self.showAgeLabel.raise_()
        self.ageLabel.raise_()
        self.eligibleLabel.raise_()
        self.genderLabel.raise_()
        self.lastStayLabel.raise_()
        self.showGenderLabel.raise_()
        self.showLastStayLabel.raise_()
        self.showEligibleLabel.raise_()
        self.buildingIdLabel.raise_()
        self.locationLabel.raise_()
        self.bedsAvaliableLabel.raise_()
        self.showBuildingIdLabel.raise_()
        self.showLocationLabel.raise_()
        self.rightArrowToolButton.raise_()
        self.leftArrowToolButton.raise_()
        self.showBedAvaliableLabel.raise_()
        self.homePushButton.raise_()
        self.backButton.raise_()
        self.adminDashboardLabel_2.raise_()
        self.logOutButton.raise_()
        self.logoLabel.raise_()
        BuildingSelection3.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BuildingSelection3)
        self.statusbar.setObjectName("statusbar")
        BuildingSelection3.setStatusBar(self.statusbar)

        self.retranslateUi(BuildingSelection3)
        QtCore.QMetaObject.connectSlotsByName(BuildingSelection3)

    def retranslateUi(self, BuildingSelection3):
        _translate = QtCore.QCoreApplication.translate
        BuildingSelection3.setWindowTitle(_translate("BuildingSelection3", "Building Selection 3"))
        self.nameLabel.setText(_translate("BuildingSelection3", "Name"))
        self.eligibleLabel.setText(_translate("BuildingSelection3", "Eligible"))
        self.genderLabel.setText(_translate("BuildingSelection3", "Gender"))
        self.ageLabel.setText(_translate("BuildingSelection3", "Age"))
        self.lastStayLabel.setText(_translate("BuildingSelection3", "Last Stay"))
        self.bookBedPushButton.setText(_translate("BuildingSelection3", "Find Alternative"))
        self.showNameLabel.setText(_translate("BuildingSelection3", "Anas Salah "))
        self.showGenderLabel.setText(_translate("BuildingSelection3", "Male"))
        self.showAgeLabel.setText(_translate("BuildingSelection3", "21"))
        self.showEligibleLabel.setText(_translate("BuildingSelection3", "Yes"))
        self.showLastStayLabel.setText(_translate("BuildingSelection3", "<html><head/><body><p align=\"center\">5 days ago</p></body></html>"))
        self.buildingIdLabel.setText(_translate("BuildingSelection3", "Building ID"))
        self.locationLabel.setText(_translate("BuildingSelection3", "Location"))
        self.bedsAvaliableLabel.setText(_translate("BuildingSelection3", "Beds Avaliable"))
        self.showBuildingIdLabel.setText(_translate("BuildingSelection3", "D"))
        self.showLocationLabel.setText(_translate("BuildingSelection3", "<html><head/><body><p>الكوربه, مصر الجديدة 21</p></body></html>"))
        self.rightArrowToolButton.setText(_translate("BuildingSelection3", "..."))
        self.leftArrowToolButton.setText(_translate("BuildingSelection3", "..."))
        self.showBedAvaliableLabel.setText(_translate("BuildingSelection3", "D"))
        self.homePushButton.setText(_translate("BuildingSelection3", "Home"))
        self.adminDashboardLabel_2.setText(_translate("BuildingSelection3", "Building Alternative"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BuildingSelection3 = QtWidgets.QMainWindow()
    ui = Ui_BuildingSelection3()
    ui.setupUi(BuildingSelection3)
    BuildingSelection3.show()
    sys.exit(app.exec_())
