# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reservation.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# import images_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reservation(object):
    def setupUi(self, Reservation):
        Reservation.setObjectName("Reservation")
        Reservation.resize(1200, 600)
        Reservation.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Reservation)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel_image = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel_image.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.logoLabel_image.setObjectName("logoLabel_image")
        self.alternativeBuildingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.alternativeBuildingsLabel.setGeometry(QtCore.QRect(100, 100, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.alternativeBuildingsLabel.setFont(font)
        self.alternativeBuildingsLabel.setObjectName("alternativeBuildingsLabel")
        self.bookBedPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.bookBedPushButton.setGeometry(QtCore.QRect(470, 500, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bookBedPushButton.setFont(font)
        self.bookBedPushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:20px;\n"
"padding: 10px; \n"
"background-color: rgb(140, 140, 140);\n"
"")
        self.bookBedPushButton.setObjectName("bookBedPushButton")
        Reservation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Reservation)
        self.statusbar.setObjectName("statusbar")
        Reservation.setStatusBar(self.statusbar)

        self.retranslateUi(Reservation)
        QtCore.QMetaObject.connectSlotsByName(Reservation)

    def retranslateUi(self, Reservation):
        _translate = QtCore.QCoreApplication.translate
        Reservation.setWindowTitle(_translate("Reservation", "Reservation"))
        self.logoLabel_image.setText(_translate("Reservation", "<html><head/><body><p><img src=\":/newPrefix/imageedit_2_5347177992.jpg\"/></p></body></html>"))
        self.alternativeBuildingsLabel.setText(_translate("Reservation", "Bed Reservation"))
        self.bookBedPushButton.setText(_translate("Reservation", "Confirm Booking"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Reservation = QtWidgets.QMainWindow()
    ui = Ui_Reservation()
    ui.setupUi(Reservation)
    Reservation.show()
    sys.exit(app.exec_())
