# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reservations_Managment.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Reservations_Managment(object):
    def setupUi(self, Reservations_Managment):
        Reservations_Managment.setObjectName("Reservations_Managment")
        Reservations_Managment.resize(1200, 600)
        Reservations_Managment.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Reservations_Managment)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel_image = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel_image.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.logoLabel_image.setObjectName("logoLabel_image")
        self.adminDashboardLabel = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel.setGeometry(QtCore.QRect(120, 100, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.adminDashboardLabel.setFont(font)
        self.adminDashboardLabel.setObjectName("adminDashboardLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setGeometry(QtCore.QRect(50, 200, 531, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setStyleSheet("color: rgb(104, 104, 104);\n"
"text-align: center;")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.viewReservationsPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewReservationsPushButton.setGeometry(QtCore.QRect(710, 290, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.viewReservationsPushButton.setFont(font)
        self.viewReservationsPushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: Center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.viewReservationsPushButton.setObjectName("viewReservationsPushButton")
        self.modifyReservationspushButton = QtWidgets.QPushButton(self.centralwidget)
        self.modifyReservationspushButton.setGeometry(QtCore.QRect(710, 400, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.modifyReservationspushButton.setFont(font)
        self.modifyReservationspushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.modifyReservationspushButton.setObjectName("modifyReservationspushButton")
        Reservations_Managment.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Reservations_Managment)
        self.statusbar.setObjectName("statusbar")
        Reservations_Managment.setStatusBar(self.statusbar)

        self.retranslateUi(Reservations_Managment)
        QtCore.QMetaObject.connectSlotsByName(Reservations_Managment)

    def retranslateUi(self, Reservations_Managment):
        _translate = QtCore.QCoreApplication.translate
        Reservations_Managment.setWindowTitle(_translate("Reservations_Managment", "Reservations Managment"))
        self.logoLabel_image.setText(_translate("Reservations_Managment", "<html><head/><body><p><img src=\":/newPrefix/imageedit_2_5347177992.jpg\"/></p></body></html>"))
        self.adminDashboardLabel.setText(_translate("Reservations_Managment", "Admin Dashboard"))
        self.welcomeLabel.setText(_translate("Reservations_Managment", "Reservations Managment"))
        self.viewReservationsPushButton.setText(_translate("Reservations_Managment", "View Reservations"))
        self.modifyReservationspushButton.setText(_translate("Reservations_Managment", "Modify Reservations"))
#import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Reservations_Managment = QtWidgets.QMainWindow()
    ui = Ui_Reservations_Managment()
    ui.setupUi(Reservations_Managment)
    Reservations_Managment.show()
    sys.exit(app.exec_())
