# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resident_Info_Sucess.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Building_Selection as BS

class Ui_Resident_Info_Sucess(object):

    def showBuildingSelection(self):
        self.BuildingSelection = QtWidgets.QMainWindow()
        self.ui = BS.Ui_BuildingSelection()
        self.ui.setupUi(self.BuildingSelection)
        self.BuildingSelection.show()
        # Resident_Info_Sucess.close()

    def setupUi(self, Resident_Info_Sucess):
        Resident_Info_Sucess.setObjectName("Resident_Info_Sucess")
        Resident_Info_Sucess.resize(1200, 600)
        Resident_Info_Sucess.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Resident_Info_Sucess)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel_image = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel_image.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.logoLabel_image.setObjectName("logoLabel_image")
        self.residentLabel = QtWidgets.QLabel(self.centralwidget)
        self.residentLabel.setGeometry(QtCore.QRect(120, 100, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.residentLabel.setFont(font)
        self.residentLabel.setObjectName("residentLabel")
        self.instructionLabel = QtWidgets.QLabel(self.centralwidget)
        self.instructionLabel.setGeometry(QtCore.QRect(120, 190, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.instructionLabel.setFont(font)
        self.instructionLabel.setStyleSheet("color: rgb(161, 161, 161);")
        self.instructionLabel.setObjectName("instructionLabel")
        self.nationalIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nationalIdLineEdit.setGeometry(QtCore.QRect(120, 260, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nationalIdLineEdit.setFont(font)
        self.nationalIdLineEdit.setStyleSheet("border-radius:0px;\n"
"border-bottom: 5px solid #3c79b5;\n"
"padding-bottom:25px;\n"
"color: rgb(179, 179, 179);\n"
"\n"
"")
        self.nationalIdLineEdit.setInputMask("")
        self.nationalIdLineEdit.setObjectName("nationalIdLineEdit")
        self.showResidentInfoPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.showResidentInfoPushButton.setGeometry(QtCore.QRect(110, 350, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.showResidentInfoPushButton.setFont(font)
        self.showResidentInfoPushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.showResidentInfoPushButton.setObjectName("showResidentInfoPushButton")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(630, 190, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.eligibleLabel = QtWidgets.QLabel(self.centralwidget)
        self.eligibleLabel.setGeometry(QtCore.QRect(960, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.eligibleLabel.setFont(font)
        self.eligibleLabel.setObjectName("eligibleLabel")
        self.genderLabel = QtWidgets.QLabel(self.centralwidget)
        self.genderLabel.setGeometry(QtCore.QRect(960, 170, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.ageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel.setGeometry(QtCore.QRect(640, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.lastStayLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastStayLabel.setGeometry(QtCore.QRect(830, 380, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lastStayLabel.setFont(font)
        self.lastStayLabel.setObjectName("lastStayLabel")
        self.nextPushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.showBuildingSelection())
        self.nextPushButton.setGeometry(QtCore.QRect(440, 510, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.nextPushButton.setFont(font)
        self.nextPushButton.setStyleSheet("background-color: rgb(0, 100, 150);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.nextPushButton.setObjectName("nextPushButton")
        self.showNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel.setGeometry(QtCore.QRect(630, 240, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel.setFont(font)
        self.showNameLabel.setStyleSheet("color: rgb(122, 122, 122);")
        self.showNameLabel.setObjectName("showNameLabel")
        self.showGenderLabel = QtWidgets.QLabel(self.centralwidget)
        self.showGenderLabel.setGeometry(QtCore.QRect(960, 240, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showGenderLabel.setFont(font)
        self.showGenderLabel.setStyleSheet("color: rgb(122, 122, 122);")
        self.showGenderLabel.setObjectName("showGenderLabel")
        self.showAgeLabel = QtWidgets.QLabel(self.centralwidget)
        self.showAgeLabel.setGeometry(QtCore.QRect(640, 340, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showAgeLabel.setFont(font)
        self.showAgeLabel.setStyleSheet("color: rgb(122, 122, 122);")
        self.showAgeLabel.setObjectName("showAgeLabel")
        self.showEligibleLabel = QtWidgets.QLabel(self.centralwidget)
        self.showEligibleLabel.setGeometry(QtCore.QRect(960, 340, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showEligibleLabel.setFont(font)
        self.showEligibleLabel.setStyleSheet("color: rgb(122, 122, 122);")
        self.showEligibleLabel.setObjectName("showEligibleLabel")
        self.showLastStayLabel = QtWidgets.QLabel(self.centralwidget)
        self.showLastStayLabel.setGeometry(QtCore.QRect(760, 430, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showLastStayLabel.setFont(font)
        self.showLastStayLabel.setStyleSheet("text-align: center;\n"
"color: rgb(122, 122, 122);")
        self.showLastStayLabel.setObjectName("showLastStayLabel")
        Resident_Info_Sucess.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Resident_Info_Sucess)
        self.statusbar.setObjectName("statusbar")
        Resident_Info_Sucess.setStatusBar(self.statusbar)

        self.retranslateUi(Resident_Info_Sucess)
        QtCore.QMetaObject.connectSlotsByName(Resident_Info_Sucess)

    def retranslateUi(self, Resident_Info_Sucess):
        _translate = QtCore.QCoreApplication.translate
        Resident_Info_Sucess.setWindowTitle(_translate("Resident_Info_Sucess", "Resident Info Sucess"))
        self.logoLabel_image.setText(_translate("Resident_Info_Sucess", "<html><head/><body><p><img src=\":/newPrefix/imageedit_2_5347177992.jpg\"/></p></body></html>"))
        self.residentLabel.setText(_translate("Resident_Info_Sucess", "Resident Info."))
        self.instructionLabel.setText(_translate("Resident_Info_Sucess", "Enter the resident\'s National ID"))
        self.nationalIdLineEdit.setPlaceholderText(_translate("Resident_Info_Sucess", "National ID"))
        self.showResidentInfoPushButton.setText(_translate("Resident_Info_Sucess", "Show Resident Info"))
        self.nameLabel.setText(_translate("Resident_Info_Sucess", "Name"))
        self.eligibleLabel.setText(_translate("Resident_Info_Sucess", "Eligible"))
        self.genderLabel.setText(_translate("Resident_Info_Sucess", "Gender"))
        self.ageLabel.setText(_translate("Resident_Info_Sucess", "Age"))
        self.lastStayLabel.setText(_translate("Resident_Info_Sucess", "Last Stay"))
        self.nextPushButton.setText(_translate("Resident_Info_Sucess", "Next"))
        self.showNameLabel.setText(_translate("Resident_Info_Sucess", "Anas Salah "))
        self.showGenderLabel.setText(_translate("Resident_Info_Sucess", "Male"))
        self.showAgeLabel.setText(_translate("Resident_Info_Sucess", "21"))
        self.showEligibleLabel.setText(_translate("Resident_Info_Sucess", "Yes"))
        self.showLastStayLabel.setText(_translate("Resident_Info_Sucess", "<html><head/><body><p align=\"center\">5 days ago</p></body></html>"))
#import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Resident_Info_Sucess = QtWidgets.QMainWindow()
    ui = Ui_Resident_Info_Sucess()
    ui.setupUi(Resident_Info_Sucess)
    Resident_Info_Sucess.show()
    sys.exit(app.exec_())
