# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resident_Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Resident_Info_Sucess as RS
from view import gui as G


class Ui_Resident_Info(object):

    def logOut(self):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()

    def backButton(self):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()

    def showResidentInfoSucess(self):
        self.Resident_Info_Sucess = QtWidgets.QMainWindow()
        self.ui = RS.Ui_Resident_Info_Sucess()
        self.ui.setupUi(self.Resident_Info_Sucess)
        self.Resident_Info_Sucess.show()
        # Resident_Info.close()

    def setupUi(self, Resident_Info):
        Resident_Info.setObjectName("Resident_Info")
        Resident_Info.resize(1200, 600)
        Resident_Info.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(Resident_Info)
        self.centralwidget.setObjectName("centralwidget")
        self.instructionLabel = QtWidgets.QLabel(self.centralwidget)
        self.instructionLabel.setGeometry(QtCore.QRect(120, 190, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.instructionLabel.setFont(font)
        self.instructionLabel.setStyleSheet("color: rgb(161, 161, 161);")
        self.instructionLabel.setObjectName("instructionLabel")
        self.nationalIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nationalIdLineEdit.setGeometry(QtCore.QRect(120, 260, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nationalIdLineEdit.setFont(font)
        self.nationalIdLineEdit.setStyleSheet("border-radius:0px;\n"
"border-bottom: 5px solid #3c79b5;\n"
"padding-bottom:25px;\n"
"color: rgb(170, 0, 0);"
"")
        self.nationalIdLineEdit.setInputMask("")
        self.nationalIdLineEdit.setObjectName("nationalIdLineEdit")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 20, 71, 61))
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.logOutButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.logOut())
        self.logOutButton.setGeometry(QtCore.QRect(1090, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.logOutButton.setFont(font)
        self.logOutButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(logout (2).png);\n"

"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.logOutButton.setText("")
        self.logOutButton.setObjectName("logOutButton")
        self.backButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.backButton())
        self.backButton.setGeometry(QtCore.QRect(970, 20, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.adminDashboardLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel_2.setGeometry(QtCore.QRect(110, 100, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel_2.setFont(font)
        self.adminDashboardLabel_2.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel_2.setObjectName("adminDashboardLabel_2")
        self.showButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.showResidentInfoSucess())
        self.showButton.setGeometry(QtCore.QRect(120, 360, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.showButton.setFont(font)
        self.showButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.showButton.setObjectName("showButton")
        Resident_Info.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Resident_Info)
        self.statusbar.setObjectName("statusbar")
        Resident_Info.setStatusBar(self.statusbar)

        self.retranslateUi(Resident_Info)
        QtCore.QMetaObject.connectSlotsByName(Resident_Info)

    def retranslateUi(self, Resident_Info):
        _translate = QtCore.QCoreApplication.translate
        Resident_Info.setWindowTitle(_translate("Resident_Info", "Resident Info"))
        self.instructionLabel.setText(_translate("Resident_Info", "Enter the resident\'s National ID"))
        self.nationalIdLineEdit.setPlaceholderText(_translate("Resident_Info", "National ID"))
        self.adminDashboardLabel_2.setText(_translate("Resident_Info", "Resident Info"))
        self.showButton.setText(_translate("Resident_Info", "Show"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Resident_Info = QtWidgets.QMainWindow()
    ui = Ui_Resident_Info()
    ui.setupUi(Resident_Info)
    Resident_Info.show()
    sys.exit(app.exec_())
