# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resident_Info_Sucess.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import messagebox

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit

import Building_Selection as BS
from main import main_control
from view import gui as G
import Resident_Infonew as RI


def logOut(self):
    self.LoginWindow = QtWidgets.QMainWindow()
    self.ui = G.Ui_LoginWindow()
    self.ui.setupUi(self.LoginWindow)
    self.LoginWindow.show()


def backButton(self):
    self.Resident_Info = QtWidgets.QMainWindow()
    self.ui = RI.Ui_Resident_Info()
    self.ui.setupUi(self.Resident_Info)
    self.Resident_Info.show()

class Ui_Resident_Info_Sucess(object):
    mc = main_control()

    def showBuildingSelection(self):
        result = self.mc.getGuiMsgsControl()
        if (self.nationalIdLineEdit.text() == ''):
            messagebox.showwarning('Warning', str(result[6]))
            return
        result = self.mc.getUserInfoControl(int(self.nationalIdLineEdit.text()))
        if (not result):
            result = self.mc.getGuiMsgsControl()
            messagebox.showerror('Error', result[8])
            return
        if (str(result[0][8]).lower() == 'n'):
            result = self.mc.getGuiMsgsControl()
            messagebox.showerror('Error', result[9])
            return
        self.BuildingSelection = QtWidgets.QMainWindow()
        self.ui = BS.Ui_BuildingSelection()
        self.ui.setupUi(self.BuildingSelection)
        self.BuildingSelection.show()
        # Resident_Info_Sucess.close()

    def showUserInfo(self):

        result = self.mc.getGuiMsgsControl()
        if (self.nationalIdLineEdit.text() == ''):
            messagebox.showwarning('Warning', str(result[6]))
            return
        result = self.mc.getUserInfoControl(int(self.nationalIdLineEdit.text()))
        print(result)
        if (not result):
            result = self.mc.getGuiMsgsControl()
            messagebox.showerror('Error', result[8])
            return
        main_control.userInfo = result
        _translate = QtCore.QCoreApplication.translate
        self.showNameLabel.setText(_translate("Resident_Info_Sucess", str(result[0][3])))
        self.showAgeLabel.setText(_translate("Resident_Info_Sucess", str(result[0][2])))
        self.showGenderLabel.setText(_translate("Resident_Info_Sucess", str(result[0][6])))
        self.showLastStayLabel.setText(_translate("Resident_Info_Sucess", str(result[0][7])))
        self.showEligibleLabel.setText(_translate("Resident_Info_Sucess", str(result[0][8])))
        return


    def setupUi(self, Resident_Info_Sucess):
        Resident_Info_Sucess.setObjectName("Resident_Info_Sucess")
        Resident_Info_Sucess.resize(1200, 600)
        Resident_Info_Sucess.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(Resident_Info_Sucess)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(630, 185, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.eligibleLabel = QtWidgets.QLabel(self.centralwidget)
        self.eligibleLabel.setGeometry(QtCore.QRect(960, 290, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.eligibleLabel.setFont(font)
        self.eligibleLabel.setObjectName("eligibleLabel")
        self.genderLabel = QtWidgets.QLabel(self.centralwidget)
        self.genderLabel.setGeometry(QtCore.QRect(960, 170, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.ageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel.setGeometry(QtCore.QRect(640, 290, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.lastStayLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastStayLabel.setGeometry(QtCore.QRect(830, 380, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lastStayLabel.setFont(font)
        self.lastStayLabel.setObjectName("lastStayLabel")
        self.showNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel.setGeometry(QtCore.QRect(630, 240, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel.setFont(font)
        self.showNameLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showNameLabel.setObjectName("showNameLabel")
        self.showGenderLabel = QtWidgets.QLabel(self.centralwidget)
        self.showGenderLabel.setGeometry(QtCore.QRect(960, 240, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showGenderLabel.setFont(font)
        self.showGenderLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showGenderLabel.setObjectName("showGenderLabel")
        self.showAgeLabel = QtWidgets.QLabel(self.centralwidget)
        self.showAgeLabel.setGeometry(QtCore.QRect(640, 340, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showAgeLabel.setFont(font)
        self.showAgeLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showAgeLabel.setObjectName("showAgeLabel")
        self.showEligibleLabel = QtWidgets.QLabel(self.centralwidget)
        self.showEligibleLabel.setGeometry(QtCore.QRect(960, 340, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showEligibleLabel.setFont(font)
        self.showEligibleLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showEligibleLabel.setObjectName("showEligibleLabel")
        self.showLastStayLabel = QtWidgets.QLabel(self.centralwidget)
        self.showLastStayLabel.setGeometry(QtCore.QRect(760, 430, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showLastStayLabel.setFont(font)
        self.showLastStayLabel.setStyleSheet("text-align: center;\n"
"color: rgb(170, 0, 0);")
        self.showLastStayLabel.setObjectName("showLastStayLabel")
        self.adminDashboardLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel_2.setGeometry(QtCore.QRect(110, 90, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel_2.setFont(font)
        self.adminDashboardLabel_2.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel_2.setObjectName("adminDashboardLabel_2")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 20, 71, 61))
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.backButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.backButton())
        self.backButton.setGeometry(QtCore.QRect(970, 20, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.logOutButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.logOut())
        self.logOutButton.setGeometry(QtCore.QRect(1090, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.logOutButton.setFont(font)
        self.logOutButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(logout (2).png);\n"

"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.logOutButton.setText("")
        self.logOutButton.setObjectName("logOutButton")
        self.bookButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.showBuildingSelection())
        self.bookButton.setGeometry(QtCore.QRect(420, 500, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.bookButton.setFont(font)
        self.bookButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.bookButton.setObjectName("bookButton")
        Resident_Info_Sucess.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Resident_Info_Sucess)
        self.statusbar.setObjectName("statusbar")
        Resident_Info_Sucess.setStatusBar(self.statusbar)

        self.retranslateUi(Resident_Info_Sucess)
        QtCore.QMetaObject.connectSlotsByName(Resident_Info_Sucess)

    def retranslateUi(self, Resident_Info_Sucess):
        _translate = QtCore.QCoreApplication.translate
        Resident_Info_Sucess.setWindowTitle(_translate("Resident_Info_Sucess", "Resident Info Sucess"))
        self.nameLabel.setText(_translate("Resident_Info_Sucess", "Name"))
        self.eligibleLabel.setText(_translate("Resident_Info_Sucess", "Eligible"))
        self.genderLabel.setText(_translate("Resident_Info_Sucess", "Gender"))
        self.ageLabel.setText(_translate("Resident_Info_Sucess", "Age"))
        self.lastStayLabel.setText(_translate("Resident_Info_Sucess", "Last Stay"))
        self.showNameLabel.setText(_translate("Resident_Info_Sucess", "Anas Salah "))
        self.showGenderLabel.setText(_translate("Resident_Info_Sucess", "Male"))
        self.showAgeLabel.setText(_translate("Resident_Info_Sucess", "21"))
        self.showEligibleLabel.setText(_translate("Resident_Info_Sucess", "Yes"))
        self.showLastStayLabel.setText(_translate("Resident_Info_Sucess", "<html><head/><body><p align=\"center\">5 days ago</p></body></html>"))
        self.adminDashboardLabel_2.setText(_translate("Resident_Info_Sucess", "Resident Info"))
        self.bookButton.setText(_translate("Resident_Info_Sucess", "Book"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Resident_Info_Sucess = QtWidgets.QMainWindow()
    ui = Ui_Resident_Info_Sucess()
    ui.setupUi(Resident_Info_Sucess)
    Resident_Info_Sucess.show()
    sys.exit(app.exec_())
