# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resident_Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Resident_Info_Sucess as RS


class Ui_Resident_Info(object):

    def showResidentInfoSucess(self):
        self.Resident_Info_Sucess = QtWidgets.QMainWindow()
        self.ui = RS.Ui_Resident_Info_Sucess()
        self.ui.setupUi(self.Resident_Info_Sucess)
        self.Resident_Info_Sucess.show()
        # Resident_Info.close()

    def setupUi(self, Resident_Info):
        Resident_Info.setObjectName("Resident_Info")
        Resident_Info.resize(1200, 600)
        Resident_Info.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(Resident_Info)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel_image = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel_image.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.logoLabel_image.setObjectName("logoLabel_image")
        self.residentLabel = QtWidgets.QLabel(self.centralwidget)
        self.residentLabel.setGeometry(QtCore.QRect(120, 100, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.residentLabel.setFont(font)
        self.residentLabel.setObjectName("residentLabel")
        self.instructionLabel = QtWidgets.QLabel(self.centralwidget)
        self.instructionLabel.setGeometry(QtCore.QRect(120, 190, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.instructionLabel.setFont(font)
        self.instructionLabel.setStyleSheet("color: rgb(161, 161, 161);")
        self.instructionLabel.setObjectName("instructionLabel")
        self.nationalIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nationalIdLineEdit.setGeometry(QtCore.QRect(120, 260, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nationalIdLineEdit.setFont(font)
        self.nationalIdLineEdit.setStyleSheet("border-radius:0px;\n"
"border-bottom: 5px solid #3c79b5;\n"
"padding-bottom:25px;\n"
"")
        self.nationalIdLineEdit.setInputMask("")
        self.nationalIdLineEdit.setObjectName("nationalIdLineEdit")
        self.showResidentInfoPushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.showResidentInfoSucess())
        self.showResidentInfoPushButton.setGeometry(QtCore.QRect(110, 350, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.showResidentInfoPushButton.setFont(font)
        self.showResidentInfoPushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.showResidentInfoPushButton.setObjectName("showResidentInfoPushButton")
        Resident_Info.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Resident_Info)
        self.statusbar.setObjectName("statusbar")
        Resident_Info.setStatusBar(self.statusbar)

        self.retranslateUi(Resident_Info)
        QtCore.QMetaObject.connectSlotsByName(Resident_Info)

    def retranslateUi(self, Resident_Info):
        _translate = QtCore.QCoreApplication.translate
        Resident_Info.setWindowTitle(_translate("Resident_Info", "Resident Info"))
        self.logoLabel_image.setText(_translate("Resident_Info", "<html><head/><body><p><img src=\":/newPrefix/imageedit_2_5347177992.jpg\"/></p></body></html>"))
        self.residentLabel.setText(_translate("Resident_Info", "Resident Info."))
        self.instructionLabel.setText(_translate("Resident_Info", "Enter the resident\'s National ID"))
        self.nationalIdLineEdit.setPlaceholderText(_translate("Resident_Info", "National ID"))
        self.showResidentInfoPushButton.setText(_translate("Resident_Info", "Show Resident Info"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Resident_Info = QtWidgets.QMainWindow()
    ui = Ui_Resident_Info()
    ui.setupUi(Resident_Info)
    Resident_Info.show()
    sys.exit(app.exec_())
