# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import Employees_Managment as EM
import Buildings_Managment as BM
import Reservations_Managment as RM
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Admin_Dashboard(object):

    def showEmployessManagment(self):
        self.Employees_Managment = QtWidgets.QMainWindow()
        self.ui = EM.Ui_Employees_Managment()
        self.ui.setupUi(self.Employees_Managment)
        self.Employees_Managment.show()
        #Admin_Dashboard.close()

    def showBuildingManagment(self):
        self.Buildings_Managment = QtWidgets.QMainWindow()
        self.ui = BM.Ui_Buildings_Managment()
        self.ui.setupUi(self.Buildings_Managment)
        self.Buildings_Managment.show()
        #Admin_Dashboard.close()

    def showReservationsManagment(self):
        self.Reservations_Managment = QtWidgets.QMainWindow()
        self.ui = RM.Ui_Reservations_Managment()
        self.ui.setupUi(self.Reservations_Managment)
        self.Reservations_Managment.show()
        #Admin_Dashboard.close()


    def setupUi(self, Admin_Dashboard):
        Admin_Dashboard.setObjectName("Admin_Dashboard")
        Admin_Dashboard.resize(1200, 600)
        Admin_Dashboard.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(Admin_Dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel_image = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel_image.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.logoLabel_image.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);")
        self.logoLabel_image.setObjectName("logoLabel_image")
        self.adminDashboardLabel = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel.setGeometry(QtCore.QRect(120, 100, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.adminDashboardLabel.setFont(font)
        self.adminDashboardLabel.setObjectName("adminDashboardLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setGeometry(QtCore.QRect(150, 210, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setStyleSheet("color: rgb(104, 104, 104);\n"
"text-align: center;")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.employeesManagmentPushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.showEmployessManagment())
        self.employeesManagmentPushButton.setGeometry(QtCore.QRect(680, 240, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.employeesManagmentPushButton.setFont(font)
        self.employeesManagmentPushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.employeesManagmentPushButton.setObjectName("employeesManagmentPushButton")
        self.buildingManagmentpushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.showBuildingManagment())
        self.buildingManagmentpushButton.setGeometry(QtCore.QRect(680, 330, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buildingManagmentpushButton.setFont(font)
        self.buildingManagmentpushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.buildingManagmentpushButton.setObjectName("buildingManagmentpushButton")
        self.reservationsManagmentPushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.showReservationsManagment())
        self.reservationsManagmentPushButton.setGeometry(QtCore.QRect(680, 430, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.reservationsManagmentPushButton.setFont(font)
        self.reservationsManagmentPushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.reservationsManagmentPushButton.setObjectName("reservationsManagmentPushButton")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.logo_label.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);")
        self.logo_label.setText("")
        self.logo_label.setObjectName("logo_label")
        Admin_Dashboard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Admin_Dashboard)
        self.statusbar.setObjectName("statusbar")
        Admin_Dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(Admin_Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Admin_Dashboard)

    def retranslateUi(self, Admin_Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Admin_Dashboard.setWindowTitle(_translate("Admin_Dashboard", "Admin Dashboard"))
        self.logoLabel_image.setText(_translate("Admin_Dashboard", "<html><head/><body><p><br/></p></body></html>"))
        self.adminDashboardLabel.setText(_translate("Admin_Dashboard", "Admin Dashboard"))
        self.welcomeLabel.setText(_translate("Admin_Dashboard", "Welcome !"))
        self.employeesManagmentPushButton.setText(_translate("Admin_Dashboard", "Employees Managment"))
        self.buildingManagmentpushButton.setText(_translate("Admin_Dashboard", "Building Managment"))
        self.reservationsManagmentPushButton.setText(_translate("Admin_Dashboard", "Reservations Managment"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Admin_Dashboard = QtWidgets.QMainWindow()
    ui = Ui_Admin_Dashboard()
    ui.setupUi(Admin_Dashboard)
    Admin_Dashboard.show()
    sys.exit(app.exec_())
