# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Employees_Managment.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import addNewEmployees as addE
import modifyEmployee as mE
import deleteEmployee as DE

class Ui_Employees_Managment(object):

    def showAddNewEmployees(self):
        self.addNewEmployee = QtWidgets.QMainWindow()
        self.ui = addE.Ui_addNewEmployee()
        self.ui.setupUi(self.addNewEmployee)
        self.addNewEmployee.show()
        #Employees_Managment.close()

    def showModifyEmployees(self):
        self.modifyEmployee = QtWidgets.QMainWindow()
        self.ui = mE.Ui_modifyEmployee()
        self.ui.setupUi(self.modifyEmployee)
        self.modifyEmployee.show()
        #Employees_Managment.close()


    def showaDeleteEmployees(self):
        self.deleteEmployee = QtWidgets.QMainWindow()
        self.ui = DE.Ui_deleteEmployee()
        self.ui.setupUi(self.deleteEmployee)
        self.deleteEmployee.show()
        #Employees_Managment.close()



    def setupUi(self, Employees_Managment):
        Employees_Managment.setObjectName("Employees_Managment")
        Employees_Managment.resize(1200, 600)
        Employees_Managment.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Employees_Managment)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel_image = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel_image.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.logoLabel_image.setObjectName("logoLabel_image")
        self.adminDashboardLabel = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel.setGeometry(QtCore.QRect(120, 100, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.adminDashboardLabel.setFont(font)
        self.adminDashboardLabel.setObjectName("adminDashboardLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setGeometry(QtCore.QRect(60, 190, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setStyleSheet("color: rgb(104, 104, 104);\n"
"text-align: center;")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.addNewEmployeePushButton = QtWidgets.QPushButton(self.centralwidget,  clicked=lambda: self.showAddNewEmployees())
        self.addNewEmployeePushButton.setGeometry(QtCore.QRect(680, 250, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addNewEmployeePushButton.setFont(font)
        self.addNewEmployeePushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.addNewEmployeePushButton.setObjectName("addNewEmployeePushButton")
        self.modifyEmployeePushButton = QtWidgets.QPushButton(self.centralwidget,  clicked=lambda: self.showModifyEmployees())
        self.modifyEmployeePushButton.setGeometry(QtCore.QRect(680, 340, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.modifyEmployeePushButton.setFont(font)
        self.modifyEmployeePushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.modifyEmployeePushButton.setObjectName("modifyEmployeePushButton")
        self.deleteEmployeePushButton = QtWidgets.QPushButton(self.centralwidget,  clicked=lambda: self.showaDeleteEmployees())
        self.deleteEmployeePushButton.setGeometry(QtCore.QRect(680, 440, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.deleteEmployeePushButton.setFont(font)
        self.deleteEmployeePushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.deleteEmployeePushButton.setObjectName("deleteEmployeePushButton")
        Employees_Managment.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Employees_Managment)
        self.statusbar.setObjectName("statusbar")
        Employees_Managment.setStatusBar(self.statusbar)

        self.retranslateUi(Employees_Managment)
        QtCore.QMetaObject.connectSlotsByName(Employees_Managment)

    def retranslateUi(self, Employees_Managment):
        _translate = QtCore.QCoreApplication.translate
        Employees_Managment.setWindowTitle(_translate("Employees_Managment", "EmployeesManagment"))
        self.logoLabel_image.setText(_translate("Employees_Managment", "<html><head/><body><p><img src=\":/newPrefix/imageedit_2_5347177992.jpg\"/></p></body></html>"))
        self.adminDashboardLabel.setText(_translate("Employees_Managment", "Admin Dashboard"))
        self.welcomeLabel.setText(_translate("Employees_Managment", "Employees Managment"))
        self.addNewEmployeePushButton.setText(_translate("Employees_Managment", "Add New Employee"))
        self.modifyEmployeePushButton.setText(_translate("Employees_Managment", "Modify Employee"))
        self.deleteEmployeePushButton.setText(_translate("Employees_Managment", "Delete Employee"))
# import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Employees_Managment = QtWidgets.QMainWindow()
    ui = Ui_Employees_Managment()
    ui.setupUi(Employees_Managment)
    Employees_Managment.show()
    sys.exit(app.exec_())
