# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Building_Selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.




from tkinter import messagebox

#import Reservation_Confirmationnew as CR
import Resident_Info_Sucessnew as RI

from PyQt5 import QtCore, QtGui, QtWidgets
from main import main_control
import Reservationnew as CR
from login import gui as G

# close function
def close():
    BuildingSelection.close()
    pass


class Ui_BuildingSelection(object):
    # log out function
    def logOut(self):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()
        close()
    # back function
    def back(self):
        self.Resident_Info_Sucess = QtWidgets.QMainWindow()
        self.ui = RI.Ui_Resident_Info_Sucess()
        self.ui.setupUi(self.Resident_Info_Sucess)
        self.Resident_Info_Sucess.show()
        close()

    mc = main_control()
    
    # UI show confirmed resident info function
    def ShowConfrim(self):
        self.mc.setBID(self.showBuildingIdLabel.text())
        self.mc.setG(self.showGenderLabel.text())
        self.confrimResDashboard = QtWidgets.QMainWindow()
        self.ui = CR.Ui_Reservation()
        self.ui.setupUi(self.confrimResDashboard)
        self.confrimResDashboard.show()

    # show building info function
    def showBuilding(self):
        _translate = QtCore.QCoreApplication.translate
        # self.clearLineEdits()
        self.mc.getBuildingIDControl(main_control.empID)
        result = self.mc.getBuildingRControl()
        result1 = self.mc.getAvBedsControl()

        if (not result):
            result = self.mc.getGuiMsgsControl()
            messagebox.showerror('Error', result[8])
            return
        self.showBuildingIdLabel.setText(_translate("modifyEmployee", str(result[0][0])))
        self.showLocationLabel.setText(_translate("modifyEmployee", str(result[0][1])))
        self.showBedAvaliableLabel.setText(_translate("modifyEmployee", str(int(result1[0][0]))))
        return
    # show alternative buildings info function
    def showAltBuilding(self):
        _translate = QtCore.QCoreApplication.translate
        self.mc.incrementBuildingID()
        self.mc.buildingIDCheckControl()
        # self.clearLineEdits()

        result = self.mc.getBuildingRControl()
        result1 = self.mc.getAvBedsControl()
        if (not result):
            result = self.mc.getGuiMsgsControl()
            messagebox.showerror('Error', result[8])
            return
        self.showBuildingIdLabel.setText(_translate("modifyEmployee", str(result[0][0])))
        self.showLocationLabel.setText(_translate("modifyEmployee", str(result[0][1])))
        self.showBedAvaliableLabel.setText(_translate("modifyEmployee", str(int(result1[0][0]))))
        return

    # UI setUp function
    def setupUi(self, BuildingSelection):
        BuildingSelection.setObjectName("BuildingSelection")
        BuildingSelection.resize(1200, 600)
        BuildingSelection.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(BuildingSelection)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(660, 186, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.eligibleLabel = QtWidgets.QLabel(self.centralwidget)
        self.eligibleLabel.setGeometry(QtCore.QRect(970, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.eligibleLabel.setFont(font)
        self.eligibleLabel.setObjectName("eligibleLabel")
        self.genderLabel = QtWidgets.QLabel(self.centralwidget)
        self.genderLabel.setGeometry(QtCore.QRect(970, 180, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.genderLabel.setFont(font)
        self.genderLabel.setObjectName("genderLabel")
        self.ageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel.setGeometry(QtCore.QRect(660, 290, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.lastStayLabel = QtWidgets.QLabel(self.centralwidget)
        self.lastStayLabel.setGeometry(QtCore.QRect(810, 380, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lastStayLabel.setFont(font)
        self.lastStayLabel.setObjectName("lastStayLabel")
        self.bookBedPushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.ShowConfrim())
        self.bookBedPushButton.setGeometry(QtCore.QRect(100, 500, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.bookBedPushButton.setFont(font)
        self.bookBedPushButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.bookBedPushButton.setObjectName("bookBedPushButton")
        self.showNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel.setGeometry(QtCore.QRect(660, 240, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel.setFont(font)
        self.showNameLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showNameLabel.setObjectName("showNameLabel")
        self.showGenderLabel = QtWidgets.QLabel(self.centralwidget)
        self.showGenderLabel.setGeometry(QtCore.QRect(970, 240, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showGenderLabel.setFont(font)
        self.showGenderLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showGenderLabel.setObjectName("showGenderLabel")
        self.showAgeLabel = QtWidgets.QLabel(self.centralwidget)
        self.showAgeLabel.setGeometry(QtCore.QRect(660, 340, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showAgeLabel.setFont(font)
        self.showAgeLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showAgeLabel.setObjectName("showAgeLabel")
        self.showEligibleLabel = QtWidgets.QLabel(self.centralwidget)
        self.showEligibleLabel.setGeometry(QtCore.QRect(970, 350, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showEligibleLabel.setFont(font)
        self.showEligibleLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.showEligibleLabel.setObjectName("showEligibleLabel")
        self.showLastStayLabel = QtWidgets.QLabel(self.centralwidget)
        self.showLastStayLabel.setGeometry(QtCore.QRect(740, 430, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showLastStayLabel.setFont(font)
        self.showLastStayLabel.setStyleSheet("text-align: center;\n"
"color: rgb(170, 0, 0);")
        self.showLastStayLabel.setObjectName("showLastStayLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(630, 160, 491, 321))
        self.label_2.setStyleSheet("image: url(:/newPrefix/C:/Users/lenovo/Desktop/4.jpg);\n"
"border-radius:10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 100, 651, 491))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 75, 132, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:5px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.findAlternativePushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.showAltBuilding())
        self.findAlternativePushButton.setGeometry(QtCore.QRect(710, 500, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.findAlternativePushButton.setFont(font)
        self.findAlternativePushButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.findAlternativePushButton.setObjectName("findAlternativePushButton")
        self.showLocationLabel = QtWidgets.QLabel(self.centralwidget)
        self.showLocationLabel.setGeometry(QtCore.QRect(100, 300, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showLocationLabel.setFont(font)
        self.showLocationLabel.setStyleSheet(
"color: rgb(170, 0, 0);\n"
)
        self.showLocationLabel.setObjectName("showLocationLabel")
        self.showBedAvaliableLabel = QtWidgets.QLabel(self.centralwidget)
        self.showBedAvaliableLabel.setGeometry(QtCore.QRect(100, 395, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showBedAvaliableLabel.setFont(font)
        self.showBedAvaliableLabel.setStyleSheet(
"color: rgb(170, 0, 0);")
        self.showBedAvaliableLabel.setObjectName("showBedAvaliableLabel")
        self.locationLabel = QtWidgets.QLabel(self.centralwidget)
        self.locationLabel.setGeometry(QtCore.QRect(100, 266, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.locationLabel.setFont(font)
        self.locationLabel.setObjectName("locationLabel")
        self.buildingIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.buildingIdLabel.setGeometry(QtCore.QRect(100, 186, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buildingIdLabel.setFont(font)
        self.buildingIdLabel.setObjectName("buildingIdLabel")
        self.bedsAvaliableLabel = QtWidgets.QLabel(self.centralwidget)
        self.bedsAvaliableLabel.setGeometry(QtCore.QRect(100, 360, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.bedsAvaliableLabel.setFont(font)
        self.bedsAvaliableLabel.setObjectName("bedsAvaliableLabel")
        self.showBuildingIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.showBuildingIdLabel.setGeometry(QtCore.QRect(100, 220, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showBuildingIdLabel.setFont(font)
        self.showBuildingIdLabel.setStyleSheet(
"color: rgb(170, 0, 0);")
        self.showBuildingIdLabel.setObjectName("showBuildingIdLabel")
        self.logOutButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.logOut())
        self.logOutButton.setGeometry(QtCore.QRect(1080, 20, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.logOutButton.setFont(font)
        self.logOutButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(logout (2).png);\n"

"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.logOutButton.setText("")
        self.logOutButton.setObjectName("logOutButton")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(10, 20, 71, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setBold(False)
        font.setWeight(50)
        self.logoLabel.setFont(font)
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.adminDashboardLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel_2.setGeometry(QtCore.QRect(20, 90, 491, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel_2.setFont(font)
        self.adminDashboardLabel_2.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel_2.setObjectName("adminDashboardLabel_2")
        self.backButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda : self.back())

        self.backButton.setGeometry(QtCore.QRect(960, 20, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.label.raise_()
        self.bookBedPushButton.raise_()
        self.label_2.raise_()
        self.nameLabel.raise_()
        self.showNameLabel.raise_()
        self.showAgeLabel.raise_()
        self.ageLabel.raise_()
        self.eligibleLabel.raise_()
        self.genderLabel.raise_()
        self.lastStayLabel.raise_()
        self.showGenderLabel.raise_()
        self.showLastStayLabel.raise_()
        self.showEligibleLabel.raise_()
        self.findAlternativePushButton.raise_()
        self.showLocationLabel.raise_()
        self.showBedAvaliableLabel.raise_()
        self.locationLabel.raise_()
        self.buildingIdLabel.raise_()
        self.bedsAvaliableLabel.raise_()
        self.showBuildingIdLabel.raise_()
        self.logOutButton.raise_()
        self.logoLabel.raise_()
        self.adminDashboardLabel_2.raise_()
        self.backButton.raise_()
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1181, 581))
        self.label.setStyleSheet("background-image: url(background.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.lower()

        BuildingSelection.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BuildingSelection)
        self.statusbar.setObjectName("statusbar")
        BuildingSelection.setStatusBar(self.statusbar)

        self.retranslateUi(BuildingSelection)
        QtCore.QMetaObject.connectSlotsByName(BuildingSelection)


    def retranslateUi(self, BuildingSelection):
        _translate = QtCore.QCoreApplication.translate
        BuildingSelection.setWindowTitle(_translate("BuildingSelection", "Building Selection"))
        self.nameLabel.setText(_translate("BuildingSelection", "Name"))
        self.eligibleLabel.setText(_translate("BuildingSelection", "Eligible"))
        self.genderLabel.setText(_translate("BuildingSelection", "Gender"))
        self.ageLabel.setText(_translate("BuildingSelection", "Age"))
        self.lastStayLabel.setText(_translate("BuildingSelection", "Last Stay"))
        self.bookBedPushButton.setText(_translate("BuildingSelection", "Book Bed"))
        self.showNameLabel.setText(_translate("BuildingSelection", "Anas Salah "))
        self.showGenderLabel.setText(_translate("BuildingSelection", "Male"))
        self.showAgeLabel.setText(_translate("BuildingSelection", "21"))
        self.showEligibleLabel.setText(_translate("BuildingSelection", "Yes"))
        self.showLastStayLabel.setText(_translate("BuildingSelection", "<html><head/><body><p align=\"center\">5 days ago</p></body></html>"))
        self.findAlternativePushButton.setText(_translate("BuildingSelection", "Find Alternative"))
        self.showLocationLabel.setText(_translate("BuildingSelection", "<html><head/><body><p>الكوربه, مصر الجديدة 21</p></body></html>"))
        self.showBedAvaliableLabel.setText(_translate("BuildingSelection", "D"))
        self.locationLabel.setText(_translate("BuildingSelection", "Location"))
        self.buildingIdLabel.setText(_translate("BuildingSelection", "Building ID"))
        self.bedsAvaliableLabel.setText(_translate("BuildingSelection", "Beds Avaliable"))
        self.showBuildingIdLabel.setText(_translate("BuildingSelection", "D"))
        self.adminDashboardLabel_2.setText(_translate("BuildingSelection", "Building Occupance"))


# main
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BuildingSelection = QtWidgets.QMainWindow()
    ui = Ui_BuildingSelection()
    ui.setupUi(BuildingSelection)
    BuildingSelection.show()
    sys.exit(app.exec_())
