# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buildingAdmin_Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
import Employees_Managment2 as EM2



class Ui_buildingAdmin_Dashboard(object):

    def showEmployessManagment2(self):
        self.Employees_Managment = QtWidgets.QMainWindow()
        self.ui = EM2.Ui_Employees_Managment()
        self.ui.setupUi(self.Employees_Managment)
        self.Employees_Managment.show()
        # Admin_Dashboard.close()


    def setupUi(self, buildingAdmin_Dashboard):
        buildingAdmin_Dashboard.setObjectName("buildingAdmin_Dashboard")
        buildingAdmin_Dashboard.resize(1200, 600)
        buildingAdmin_Dashboard.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(buildingAdmin_Dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel_image = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel_image.setGeometry(QtCore.QRect(20, 20, 71, 71))
        self.logoLabel_image.setObjectName("logoLabel_image")
        self.adminDashboardLabel = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel.setGeometry(QtCore.QRect(120, 100, 561, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.adminDashboardLabel.setFont(font)
        self.adminDashboardLabel.setObjectName("adminDashboardLabel")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setGeometry(QtCore.QRect(150, 210, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.welcomeLabel.setFont(font)
        self.welcomeLabel.setStyleSheet("color: rgb(104, 104, 104);\n"
"text-align: center;")
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.employeesManagmentPushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.showEmployessManagment2())
        self.employeesManagmentPushButton.setGeometry(QtCore.QRect(680, 260, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.employeesManagmentPushButton.setFont(font)
        self.employeesManagmentPushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.employeesManagmentPushButton.setObjectName("employeesManagmentPushButton")
        self.viewReservationsPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewReservationsPushButton.setGeometry(QtCore.QRect(680, 400, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.viewReservationsPushButton.setFont(font)
        self.viewReservationsPushButton.setStyleSheet("background-color: rgb(140, 140, 140);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.viewReservationsPushButton.setObjectName("viewReservationsPushButton")
        buildingAdmin_Dashboard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(buildingAdmin_Dashboard)
        self.statusbar.setObjectName("statusbar")
        buildingAdmin_Dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(buildingAdmin_Dashboard)
        QtCore.QMetaObject.connectSlotsByName(buildingAdmin_Dashboard)

    def retranslateUi(self, buildingAdmin_Dashboard):
        _translate = QtCore.QCoreApplication.translate
        buildingAdmin_Dashboard.setWindowTitle(_translate("buildingAdmin_Dashboard", "Building Admin Dashboard"))
        self.logoLabel_image.setText(_translate("buildingAdmin_Dashboard", "<html><head/><body><p><img src=\":/newPrefix/imageedit_2_5347177992.jpg\"/></p></body></html>"))
        self.adminDashboardLabel.setText(_translate("buildingAdmin_Dashboard", "Building Admin Dashboard"))
        self.welcomeLabel.setText(_translate("buildingAdmin_Dashboard", "Welcome !"))
        self.employeesManagmentPushButton.setText(_translate("buildingAdmin_Dashboard", "Employees Managment"))
        self.viewReservationsPushButton.setText(_translate("buildingAdmin_Dashboard", "View Reservations "))
# import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    buildingAdmin_Dashboard = QtWidgets.QMainWindow()
    ui = Ui_buildingAdmin_Dashboard()
    ui.setupUi(buildingAdmin_Dashboard)
    buildingAdmin_Dashboard.show()
    sys.exit(app.exec_())
