# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addNewEmployees.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import messagebox
import sys
from main import main_control
from PyQt5 import QtCore, QtGui, QtWidgets
import Employees_Managmentnew as EM
from login import gui as G

# close function
def close():
    addNewEmployee.close()
    pass

class Ui_addNewEmployee(object):
    # logout function
    def logOut(self):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()
        close()

    # back function
    def back(self):
        self.Employees_Managment = QtWidgets.QMainWindow()
        self.ui = EM.Ui_Employees_Managment()
        self.ui.setupUi(self.Employees_Managment)
        self.Employees_Managment.show()
        close()

    # collect employee info and send to CONTROL to add into db
    def addEmployee(self):
        mc = main_control()
        result = mc.getGuiMsgsControl()
        if (self.idLineEdit.text() == '' or  self.nameLineEdit.text() == '' or  self.addressLineEdit.text() == '' or  self.dateOfBirthLineEdit.text() == '' or  self.salaryLineEdit.text() == '' or  self.contactInfoLineEdit.text() == '' or  self.dateOfDeploymentLineEdit.text() == '' or  self.adminIdLineEdit.text() == '' or  self.buildingIdLineEdit.text() == ''):
            messagebox.showwarning('Warning', str(result[3]))
            return
        print("henaho")
        emptuple = (int(self.idLineEdit.text()), self.nameLineEdit.text(), self.addressLineEdit.text(),
                    self.dateOfBirthLineEdit.text(), float(self.salaryLineEdit.text()),
                    int(self.contactInfoLineEdit.text()), self.dateOfDeploymentLineEdit.text(),
                    int(self.adminIdLineEdit.text()), int(self.buildingIdLineEdit.text()))
        isacceptable = mc.addEMployeeControl(emptuple)
        if str(isacceptable).lower() == "none":
            messagebox.showinfo('information', str(result[4]))

        else:
            ermsg2 = str(result[5])
            ermsg1 = str(isacceptable)
            ermsg = ermsg2 + " " + ermsg1
            messagebox.showerror('Error', ermsg)

  
    # UI setUp function
    def setupUi(self, addNewEmployee):
        addNewEmployee.setObjectName("addNewEmployee")
        addNewEmployee.resize(1200, 600)
        addNewEmployee.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(addNewEmployee)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(130, 300, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.showNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel.setGeometry(QtCore.QRect(130, 260, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel.setFont(font)
        self.showNameLabel.setStyleSheet("color: rgb(122, 122, 122);")
        self.showNameLabel.setObjectName("showNameLabel")
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setGeometry(QtCore.QRect(130, 210, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        self.nameLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel_2.setGeometry(QtCore.QRect(130, 400, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_2.setFont(font)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.ageLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_2.setGeometry(QtCore.QRect(130, 490, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_2.setFont(font)
        self.ageLabel_2.setObjectName("ageLabel_2")
        self.ageLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_3.setGeometry(QtCore.QRect(470, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_3.setFont(font)
        self.ageLabel_3.setObjectName("ageLabel_3")
        self.ageLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_4.setGeometry(QtCore.QRect(470, 300, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_4.setFont(font)
        self.ageLabel_4.setObjectName("ageLabel_4")
        self.ageLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_5.setGeometry(QtCore.QRect(470, 400, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_5.setFont(font)
        self.ageLabel_5.setObjectName("ageLabel_5")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.addEmployee())
        self.addButton.setGeometry(QtCore.QRect(590, 510, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}")
        self.addButton.setObjectName("addButton")
        self.idLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idLineEdit.setGeometry(QtCore.QRect(130, 260, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLineEdit.setFont(font)
        self.idLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.idLineEdit.setObjectName("idLineEdit")
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setGeometry(QtCore.QRect(130, 350, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.addressLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.addressLineEdit.setGeometry(QtCore.QRect(130, 440, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addressLineEdit.setFont(font)
        self.addressLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.dateOfBirthLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dateOfBirthLineEdit.setGeometry(QtCore.QRect(130, 530, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateOfBirthLineEdit.setFont(font)
        self.dateOfBirthLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.dateOfBirthLineEdit.setObjectName("dateOfBirthLineEdit")
        self.salaryLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.salaryLineEdit.setGeometry(QtCore.QRect(470, 250, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.salaryLineEdit.setFont(font)
        self.salaryLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.salaryLineEdit.setObjectName("salaryLineEdit")
        self.contactInfoLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.contactInfoLineEdit.setGeometry(QtCore.QRect(470, 350, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contactInfoLineEdit.setFont(font)
        self.contactInfoLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.contactInfoLineEdit.setObjectName("contactInfoLineEdit")
        self.dateOfDeploymentLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dateOfDeploymentLineEdit.setGeometry(QtCore.QRect(470, 450, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateOfDeploymentLineEdit.setFont(font)
        self.dateOfDeploymentLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.dateOfDeploymentLineEdit.setObjectName("dateOfDeploymentLineEdit")
        self.buildingIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.buildingIdLineEdit.setGeometry(QtCore.QRect(850, 450, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buildingIdLineEdit.setFont(font)
        self.buildingIdLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.buildingIdLineEdit.setObjectName("buildingIdLineEdit")
        self.ageLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_6.setGeometry(QtCore.QRect(850, 300, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_6.setFont(font)
        self.ageLabel_6.setObjectName("ageLabel_6")
        self.adminIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.adminIdLineEdit.setGeometry(QtCore.QRect(850, 250, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adminIdLineEdit.setFont(font)
        self.adminIdLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.adminIdLineEdit.setObjectName("adminIdLineEdit")
        self.buildingAdminIdLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.buildingAdminIdLineEdit.setGeometry(QtCore.QRect(850, 350, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buildingAdminIdLineEdit.setFont(font)
        self.buildingAdminIdLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.buildingAdminIdLineEdit.setObjectName("buildingAdminIdLineEdit")
        self.ageLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_7.setGeometry(QtCore.QRect(850, 400, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_7.setFont(font)
        self.ageLabel_7.setObjectName("ageLabel_7")
        self.ageLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_8.setGeometry(QtCore.QRect(850, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_8.setFont(font)
        self.ageLabel_8.setObjectName("ageLabel_8")
        self.adminDashboardLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel_2.setGeometry(QtCore.QRect(50, 100, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel_2.setFont(font)
        self.adminDashboardLabel_2.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel_2.setObjectName("adminDashboardLabel_2")
        self.idLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_3.setGeometry(QtCore.QRect(160, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_3.setFont(font)
        self.idLabel_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_3.setText("")
        self.idLabel_3.setObjectName("idLabel_3")
        self.idLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_2.setGeometry(QtCore.QRect(410, 100, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_2.setFont(font)
        self.idLabel_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(businessman (1).png);")
        self.idLabel_2.setText("")
        self.idLabel_2.setObjectName("idLabel_2")
        self.backButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.back())
        self.backButton.setGeometry(QtCore.QRect(970, 20, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 20, 71, 61))
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.logOutButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.logOut())
        self.logOutButton.setGeometry(QtCore.QRect(1090, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.logOutButton.setFont(font)
        self.logOutButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(logout (2).png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.logOutButton.setText("")
        self.logOutButton.setObjectName("logOutButton")
        self.idLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_4.setGeometry(QtCore.QRect(1020, 300, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_4.setFont(font)
        self.idLabel_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_4.setText("")
        self.idLabel_4.setObjectName("idLabel_4")
        self.idLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_5.setGeometry(QtCore.QRect(930, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_5.setFont(font)
        self.idLabel_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_5.setText("")
        self.idLabel_5.setObjectName("idLabel_5")
        self.idLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_6.setGeometry(QtCore.QRect(950, 400, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_6.setFont(font)
        self.idLabel_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_6.setText("")
        self.idLabel_6.setObjectName("idLabel_6")
        addNewEmployee.setCentralWidget(self.centralwidget)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1181, 581))
        self.label.setStyleSheet("background-image: url(background.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.lower()

        self.statusbar = QtWidgets.QStatusBar(addNewEmployee)
        self.statusbar.setObjectName("statusbar")
        addNewEmployee.setStatusBar(self.statusbar)

        self.retranslateUi(addNewEmployee)
        QtCore.QMetaObject.connectSlotsByName(addNewEmployee)

    def retranslateUi(self, addNewEmployee):
        _translate = QtCore.QCoreApplication.translate
        addNewEmployee.setWindowTitle(_translate("addNewEmployee", "addNewEmployee"))
        self.nameLabel.setText(_translate("addNewEmployee", "Name"))
        self.showNameLabel.setText(_translate("addNewEmployee", "xx"))
        self.idLabel.setText(_translate("addNewEmployee", "Id"))
        self.nameLabel_2.setText(_translate("addNewEmployee", "Address"))
        self.ageLabel_2.setText(_translate("addNewEmployee", "Data of Birth"))
        self.ageLabel_3.setText(_translate("addNewEmployee", "Salary"))
        self.ageLabel_4.setText(_translate("addNewEmployee", "Contact Info"))
        self.ageLabel_5.setText(_translate("addNewEmployee", "Date of Deployment"))
        self.addButton.setText(_translate("addNewEmployee", "Add"))
        self.ageLabel_6.setText(_translate("addNewEmployee", "Building Admin Id"))
        self.ageLabel_7.setText(_translate("addNewEmployee", "Building Id"))
        self.ageLabel_8.setText(_translate("addNewEmployee", "Admin Id"))
        self.adminDashboardLabel_2.setText(_translate("addNewEmployee", "Add Employee"))


# main
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addNewEmployee = QtWidgets.QMainWindow()
    ui = Ui_addNewEmployee()
    ui.setupUi(addNewEmployee)
    addNewEmployee.show()
    sys.exit(app.exec_())
