# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin_Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtGui import QIcon

import Employees_Managmentnew as EM
import Buildings_Managmentnew as BM
import Reservations_Managmentnew as RM
from PyQt5 import QtCore, QtGui, QtWidgets
from login import gui as G



class Ui_Admin_Dashboard(object):

    def logOut(self,AdminDashboard):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()
        AdminDashboard.close()

    def back(self,Admin_Dashboard):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()
        Admin_Dashboard.close()

    def showEmployessManagment(self,AdminDashboard):
        self.Employees_Managment = QtWidgets.QMainWindow()
        self.ui = EM.Ui_Employees_Managment()
        self.ui.setupUi(self.Employees_Managment)
        self.Employees_Managment.show()
        AdminDashboard.close()


    def showBuildingManagment(self,AdminDashboard):
        self.Buildings_Managment = QtWidgets.QMainWindow()
        self.ui = BM.Ui_Buildings_Managment()
        self.ui.setupUi(self.Buildings_Managment)
        self.Buildings_Managment.show()
        AdminDashboard.close()


    def showReservationsManagment(self,AdminDashboard):
        self.Reservations_Managment = QtWidgets.QMainWindow()
        self.ui = RM.Ui_Reservations_Managment()
        self.ui.setupUi(self.Reservations_Managment)
        self.Reservations_Managment.show()
        AdminDashboard.close()


    def setupUi(self, Admin_Dashboard):
        Admin_Dashboard.setObjectName("Admin_Dashboard")
        Admin_Dashboard.resize(1200, 600)
        Admin_Dashboard.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(Admin_Dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.adminDashboardLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel_2.setGeometry(QtCore.QRect(420, 240, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel_2.setFont(font)
        self.adminDashboardLabel_2.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel_2.setObjectName("adminDashboardLabel_2")
        self.adminDashboardLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel_3.setGeometry(QtCore.QRect(210, 140, 631, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel_3.setFont(font)
        self.adminDashboardLabel_3.setStyleSheet("color: rgb(170, 0, 0);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel_3.setObjectName("adminDashboardLabel_3")
        self.showResidentInfoPushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.logOut(Admin_Dashboard))
        self.showResidentInfoPushButton_2.setGeometry(QtCore.QRect(1080, 30, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.showResidentInfoPushButton_2.setFont(font)
        self.showResidentInfoPushButton_2.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(logout.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n")

        self.showResidentInfoPushButton_2.setText("")
        self.showResidentInfoPushButton_2.setObjectName("showResidentInfoPushButton_2")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.showEmployessManagment(Admin_Dashboard))
        self.addButton.setGeometry(QtCore.QRect(50, 430, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.addButton.setObjectName("addButton")
        self.modifyButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.showBuildingManagment(Admin_Dashboard))
        self.modifyButton.setGeometry(QtCore.QRect(440, 430, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.modifyButton.setFont(font)
        self.modifyButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.modifyButton.setObjectName("modifyButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.showReservationsManagment(Admin_Dashboard))
        self.deleteButton.setGeometry(QtCore.QRect(820, 430, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.deleteButton.setObjectName("deleteButton")
        self.showResidentInfoPushButton_3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.back(Admin_Dashboard))
        self.showResidentInfoPushButton_3.setGeometry(QtCore.QRect(960, 30, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.showResidentInfoPushButton_3.setFont(font)
        self.showResidentInfoPushButton_3.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
""
)
        self.showResidentInfoPushButton_3.setText("")

        self.showResidentInfoPushButton_3.setObjectName("showResidentInfoPushButton_3")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(10, 30, 71, 61))
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1181, 581))
        self.label.setStyleSheet("background-image: url(d1668ee13fec4635d7f8d2a65c89d1b2.jpg);\n")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.lower()

        Admin_Dashboard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Admin_Dashboard)

        # self.label = QtWidgets.QLabel(self.centralwidget)
        # self.label.setGeometry(QtCore.QRect(10, 10, 1181, 581))
        # self.label.setStyleSheet("background-image: url(background.jpg);")
        # self.label.setText("")
        # self.label.setObjectName("label")
        # self.label.lower()

        self.statusbar.setObjectName("statusbar")
        Admin_Dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(Admin_Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Admin_Dashboard)

    def retranslateUi(self, Admin_Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Admin_Dashboard.setWindowTitle(_translate("Admin_Dashboard", "Admin Dashboard"))
        self.adminDashboardLabel_2.setText(_translate("Admin_Dashboard", "Mangament"))
        self.adminDashboardLabel_3.setText(_translate("Admin_Dashboard", "Admin Dashboard"))
        self.addButton.setText(_translate("Admin_Dashboard", "Employee"))
        self.modifyButton.setText(_translate("Admin_Dashboard", "Building"))
        self.deleteButton.setText(_translate("Admin_Dashboard", "Reservations"))



# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Admin_Dashboard = QtWidgets.QMainWindow()
#     ui = Ui_Admin_Dashboard()
#     ui.setupUi(Admin_Dashboard)
#     Admin_Dashboard.show()
#     sys.exit(app.exec_())
