# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteEmployee.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tkinter import messagebox

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit
from main import main_control
import Admin_Dashboardnew as AD
import Employees_Managmentnew as EM
from login import gui as G

# close function
def close():
    deleteEmployee.close()
    pass

class Ui_deleteEmployee(object):

    # logout function
    def logOut(self):
                self.LoginWindow = QtWidgets.QMainWindow()
                self.ui = G.Ui_LoginWindow()
                self.ui.setupUi(self.LoginWindow)
                self.LoginWindow.show()
                close()
    # back function
    def back(self):
                self.Employees_Managment = QtWidgets.QMainWindow()
                self.ui = EM.Ui_Employees_Managment()
                self.ui.setupUi(self.Employees_Managment)
                self.Employees_Managment.show()
                close()

                # collect employee info and send to CONTROL to get info from db

    # show employee function
    def showEmployee(self):
        _translate = QtCore.QCoreApplication.translate
        mc = main_control()
        result = mc.getGuiMsgsControl()
        if (self.idLineEdit.text() == ''):
            messagebox.showwarning('Warning', str(result[6]))
            return
        result = mc.getEmplyeeInfoControl(int(self.idLineEdit.text()))

        if (not result):
            result = mc.getGuiMsgsControl()
            messagebox.showerror('Error', result[8])
            return
        self.showNameLabel.insert(_translate("modifyEmployee", str(result[0][1])))
        self.showNameLabel_3.insert(_translate("modifyEmployee", str(result[0][2])))
        self.dateOfBirthLineEdit.insert(_translate("modifyEmployee", str(result[0][3])))
        self.salaryLineEdit.insert(_translate("modifyEmployee", str(result[0][4])))
        self.contactInfoLineEdit.insert(_translate("modifyEmployee", str(result[0][5])))
        self.dateOfDeploymentLineEdit.insert(_translate("modifyEmployee", str(result[0][6])))
        self.adminIdLineEdit.insert(_translate("modifyEmployee", str(result[0][7])))
        self.buildingIdLineEdit.insert(_translate("modifyEmployee", str(result[0][8])))
        return

    def deleteEmployee(self):
        mc = main_control()
        result = mc.getGuiMsgsControl()
        if (self.idLineEdit.text() == ''):
            messagebox.showwarning('Warning', str(result[6]))
            return
        isacceptable = mc.deleteEMployeeControl(self.idLineEdit.text())
        if str(isacceptable).lower() == "none":
            messagebox.showinfo('information', str(result[7]))


    def setupUi(self, deleteEmployee):
        deleteEmployee.setObjectName("deleteEmployee")
        deleteEmployee.resize(1200, 600)
        deleteEmployee.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(deleteEmployee)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(130, 300, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.showNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel.setGeometry(QtCore.QRect(130, 260, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel.setFont(font)
        self.showNameLabel.setStyleSheet("color: rgb(122, 122, 122);")
        self.showNameLabel.setObjectName("showNameLabel")
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setGeometry(QtCore.QRect(130, 210, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        self.nameLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel_2.setGeometry(QtCore.QRect(130, 400, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_2.setFont(font)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.ageLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_2.setGeometry(QtCore.QRect(130, 490, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_2.setFont(font)
        self.ageLabel_2.setObjectName("ageLabel_2")
        self.ageLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_3.setGeometry(QtCore.QRect(470, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_3.setFont(font)
        self.ageLabel_3.setObjectName("ageLabel_3")
        self.ageLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_4.setGeometry(QtCore.QRect(470, 300, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_4.setFont(font)
        self.ageLabel_4.setObjectName("ageLabel_4")
        self.ageLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_5.setGeometry(QtCore.QRect(470, 400, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_5.setFont(font)
        self.ageLabel_5.setObjectName("ageLabel_5")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.deleteEmployee())
        self.deleteButton.setGeometry(QtCore.QRect(560, 510, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.deleteButton.setObjectName("deleteButton")
        self.idLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idLineEdit.setGeometry(QtCore.QRect(130, 260, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLineEdit.setFont(font)
        self.idLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.idLineEdit.setObjectName("idLineEdit")
        self.ageLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_6.setGeometry(QtCore.QRect(850, 300, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_6.setFont(font)
        self.ageLabel_6.setObjectName("ageLabel_6")
        self.ageLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_7.setGeometry(QtCore.QRect(850, 400, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_7.setFont(font)
        self.ageLabel_7.setObjectName("ageLabel_7")
        self.ageLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_8.setGeometry(QtCore.QRect(850, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_8.setFont(font)
        self.ageLabel_8.setObjectName("ageLabel_8")
        self.showPushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.showEmployee())
        self.showPushButton.setGeometry(QtCore.QRect(290, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.showPushButton.setFont(font)
        self.showPushButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(140,140,140);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}")
        self.showPushButton.setObjectName("showPushButton")
        self.showNameLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel_3.setGeometry(QtCore.QRect(130, 340, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel_3.setFont(font)
        self.showNameLabel_3.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.showNameLabel_3.setText("")
        self.showNameLabel_3.setObjectName("showNameLabel_3")
        self.showNameLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel_4.setGeometry(QtCore.QRect(130, 440, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel_4.setFont(font)
        self.showNameLabel_4.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.showNameLabel_4.setText("")
        self.showNameLabel_4.setObjectName("showNameLabel_4")
        self.showNameLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel_5.setGeometry(QtCore.QRect(130, 530, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel_5.setFont(font)
        self.showNameLabel_5.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.showNameLabel_5.setText("")
        self.showNameLabel_5.setObjectName("showNameLabel_5")
        self.showNameLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel_6.setGeometry(QtCore.QRect(470, 250, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel_6.setFont(font)
        self.showNameLabel_6.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.showNameLabel_6.setText("")
        self.showNameLabel_6.setObjectName("showNameLabel_6")
        self.showNameLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel_7.setGeometry(QtCore.QRect(470, 350, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel_7.setFont(font)
        self.showNameLabel_7.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.showNameLabel_7.setText("")
        self.showNameLabel_7.setObjectName("showNameLabel_7")
        self.showNameLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel_8.setGeometry(QtCore.QRect(470, 450, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel_8.setFont(font)
        self.showNameLabel_8.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.showNameLabel_8.setText("")
        self.showNameLabel_8.setObjectName("showNameLabel_8")
        self.showNameLabel_9 = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel_9.setGeometry(QtCore.QRect(850, 250, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel_9.setFont(font)
        self.showNameLabel_9.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.showNameLabel_9.setText("")
        self.showNameLabel_9.setObjectName("showNameLabel_9")
        self.showNameLabel_10 = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel_10.setGeometry(QtCore.QRect(850, 360, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel_10.setFont(font)
        self.showNameLabel_10.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.showNameLabel_10.setText("")
        self.showNameLabel_10.setObjectName("showNameLabel_10")
        self.showNameLabel_11 = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel_11.setGeometry(QtCore.QRect(850, 460, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel_11.setFont(font)
        self.showNameLabel_11.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.showNameLabel_11.setText("")
        self.showNameLabel_11.setObjectName("showNameLabel_11")
        self.idLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_3.setGeometry(QtCore.QRect(190, 210, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_3.setFont(font)
        self.idLabel_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_3.setText("")
        self.idLabel_3.setObjectName("idLabel_3")
        self.idLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_4.setGeometry(QtCore.QRect(940, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_4.setFont(font)
        self.idLabel_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_4.setText("")
        self.idLabel_4.setObjectName("idLabel_4")
        self.idLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_5.setGeometry(QtCore.QRect(1010, 300, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_5.setFont(font)
        self.idLabel_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_5.setText("")
        self.idLabel_5.setObjectName("idLabel_5")
        self.idLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_6.setGeometry(QtCore.QRect(940, 400, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_6.setFont(font)
        self.idLabel_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_6.setText("")
        self.idLabel_6.setObjectName("idLabel_6")
        self.idLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_2.setGeometry(QtCore.QRect(460, 100, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_2.setFont(font)
        self.idLabel_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(businessman (1).png);")
        self.idLabel_2.setText("")
        self.idLabel_2.setObjectName("idLabel_2")
        self.adminDashboardLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel_2.setGeometry(QtCore.QRect(70, 100, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel_2.setFont(font)
        self.adminDashboardLabel_2.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel_2.setObjectName("adminDashboardLabel_2")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 20, 71, 61))
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.backButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.back())
        self.backButton.setGeometry(QtCore.QRect(970, 20, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.logOutButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.logOut())
        self.logOutButton.setGeometry(QtCore.QRect(1090, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.logOutButton.setFont(font)
        self.logOutButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(logout (2).png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.logOutButton.setText("")
        self.logOutButton.setObjectName("logOutButton")
        deleteEmployee.setCentralWidget(self.centralwidget)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1181, 581))
        self.label.setStyleSheet("background-image: url(background.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.lower()

        self.statusbar = QtWidgets.QStatusBar(deleteEmployee)
        self.statusbar.setObjectName("statusbar")
        deleteEmployee.setStatusBar(self.statusbar)

        self.retranslateUi(deleteEmployee)
        QtCore.QMetaObject.connectSlotsByName(deleteEmployee)

    def retranslateUi(self, deleteEmployee):
        _translate = QtCore.QCoreApplication.translate
        deleteEmployee.setWindowTitle(_translate("deleteEmployee", "deleteEmployee"))
        self.nameLabel.setText(_translate("deleteEmployee", "Name"))
        self.showNameLabel.setText(_translate("deleteEmployee", "xx"))
        self.idLabel.setText(_translate("deleteEmployee", "Id"))
        self.nameLabel_2.setText(_translate("deleteEmployee", "Address"))
        self.ageLabel_2.setText(_translate("deleteEmployee", "Data of Birth"))
        self.ageLabel_3.setText(_translate("deleteEmployee", "Salary"))
        self.ageLabel_4.setText(_translate("deleteEmployee", "Contact Info"))
        self.ageLabel_5.setText(_translate("deleteEmployee", "Date of Deployment"))
        self.deleteButton.setText(_translate("deleteEmployee", "Delete"))
        self.ageLabel_6.setText(_translate("deleteEmployee", "Building Admin Id"))
        self.ageLabel_7.setText(_translate("deleteEmployee", "Building Id"))
        self.ageLabel_8.setText(_translate("deleteEmployee", "Admin Id"))
        self.showPushButton.setText(_translate("deleteEmployee", "Show "))
        self.adminDashboardLabel_2.setText(_translate("deleteEmployee", "Delete Employee"))


# main function
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteEmployee = QtWidgets.QMainWindow()
    ui = Ui_deleteEmployee()
    ui.setupUi(deleteEmployee)
    deleteEmployee.show()
    sys.exit(app.exec_())
