# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteBuilding.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Admin_Dashboardnew as AD
from tkinter import messagebox
from main import main_control
from login import gui as G
import Buildings_Managmentnew as BM

# close function
def close():
    deleteBuilding.close()
    pass

class Ui_deleteBuilding(object):

    # logout function
    def logOut(self):
                self.LoginWindow = QtWidgets.QMainWindow()
                self.ui = G.Ui_LoginWindow()
                self.ui.setupUi(self.LoginWindow)
                self.LoginWindow.show()
                close()

    # back function
    def back(self):
                self.Buildings_Managment = QtWidgets.QMainWindow()
                self.ui = BM.Ui_Buildings_Managment()
                self.ui.setupUi(self.Buildings_Managment)
                self.Buildings_Managment.show()
                close()

                # collect building info and send to CONTROL to get info from db

    # show building function
    def showBuilding(self):
        _translate = QtCore.QCoreApplication.translate
        mc = main_control()
        result = mc.getGuiMsgsControl()
        if (self.idLineEdit.text() == ''):
            messagebox.showwarning('Warning', str(result[6]))
            return
        result = mc.getBuildingInfoControl(int(self.idLineEdit.text()))

        if (not result):
            result = mc.getGuiMsgsControl()
            messagebox.showerror('Error', result[8])
            return
        self.locationLineEdit.insert(_translate("modifyEmployee", str(result[0][1])))
        self.totalFloorsLineEdit.insert(_translate("modifyEmployee", str(result[0][2])))
        return

    def deleteBuilding(self):
        mc = main_control()
        result = mc.getGuiMsgsControl()
        if (self.idLineEdit.text() == ''):
            messagebox.showwarning('Warning', str(result[6]))
            return
        isacceptable = mc.deleteBuildingControl(self.idLineEdit.text())
        if str(isacceptable).lower() == "none":
            messagebox.showinfo('information', str(result[7]))

    def setupUi(self, deleteBuilding):
        deleteBuilding.setObjectName("deleteBuilding")
        deleteBuilding.resize(1200, 600)
        deleteBuilding.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(deleteBuilding)
        self.centralwidget.setObjectName("centralwidget")
        self.showPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.showPushButton.setGeometry(QtCore.QRect(280, 185, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.showPushButton.setFont(font)
        self.showPushButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(140,140,140);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}")
        self.showPushButton.setObjectName("showPushButton")
        self.ageLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_3.setGeometry(QtCore.QRect(750, 190, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_3.setFont(font)
        self.ageLabel_3.setObjectName("ageLabel_3")
        self.backPushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.back())
        self.backPushButton.setGeometry(QtCore.QRect(970, 20, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.backPushButton.setFont(font)
        self.backPushButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.backPushButton.setText("")
        self.backPushButton.setObjectName("backPushButton")
        self.ageLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_4.setGeometry(QtCore.QRect(750, 290, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_4.setFont(font)
        self.ageLabel_4.setObjectName("ageLabel_4")
        self.idLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_8.setGeometry(QtCore.QRect(890, 390, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_8.setFont(font)
        self.idLabel_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(gender-fluid.png);")
        self.idLabel_8.setText("")
        self.idLabel_8.setObjectName("idLabel_8")
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setGeometry(QtCore.QRect(120, 195, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.idLabel.setFont(font)
        self.idLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.idLabel.setObjectName("idLabel")
        self.logOutPushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.logOut())
        self.logOutPushButton.setGeometry(QtCore.QRect(1090, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.logOutPushButton.setFont(font)
        self.logOutPushButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(logout (2).png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.logOutPushButton.setText("")
        self.logOutPushButton.setObjectName("logOutPushButton")
        self.ageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel.setGeometry(QtCore.QRect(120, 290, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.nameLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel_2.setGeometry(QtCore.QRect(120, 390, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_2.setFont(font)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 20, 71, 61))
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.idLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_2.setGeometry(QtCore.QRect(410, 90, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_2.setFont(font)
        self.idLabel_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(home.png);")
        self.idLabel_2.setText("")
        self.idLabel_2.setObjectName("idLabel_2")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.deleteBuilding())
        self.deleteButton.setGeometry(QtCore.QRect(700, 500, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.deleteButton.setFont(font)
        self.deleteButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}")
        self.deleteButton.setObjectName("deleteButton")
        self.idLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_7.setGeometry(QtCore.QRect(850, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_7.setFont(font)
        self.idLabel_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(beds.png);")
        self.idLabel_7.setText("")
        self.idLabel_7.setObjectName("idLabel_7")
        self.adminDashboardLabel = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel.setGeometry(QtCore.QRect(45, 90, 361, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel.setFont(font)
        self.adminDashboardLabel.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel.setObjectName("adminDashboardLabel")
        self.ageLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_2.setGeometry(QtCore.QRect(120, 480, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_2.setFont(font)
        self.ageLabel_2.setObjectName("ageLabel_2")
        self.idLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_4.setGeometry(QtCore.QRect(220, 390, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_4.setFont(font)
        self.idLabel_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_4.setText("")
        self.idLabel_4.setObjectName("idLabel_4")
        self.idLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_3.setGeometry(QtCore.QRect(180, 190, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_3.setFont(font)
        self.idLabel_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_3.setText("")
        self.idLabel_3.setObjectName("idLabel_3")
        self.idLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_6.setGeometry(QtCore.QRect(230, 480, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_6.setFont(font)
        self.idLabel_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(plan.png);")
        self.idLabel_6.setText("")
        self.idLabel_6.setObjectName("idLabel_6")
        self.idLabel_9 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_9.setGeometry(QtCore.QRect(880, 190, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_9.setFont(font)
        self.idLabel_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(living-room.png);")
        self.idLabel_9.setText("")
        self.idLabel_9.setObjectName("idLabel_9")
        self.ageLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_5.setGeometry(QtCore.QRect(750, 390, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_5.setFont(font)
        self.ageLabel_5.setObjectName("ageLabel_5")
        self.idLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_5.setGeometry(QtCore.QRect(210, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_5.setFont(font)
        self.idLabel_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(location-pin.png);")
        self.idLabel_5.setText("")
        self.idLabel_5.setObjectName("idLabel_5")
        self.IdLabel = QtWidgets.QLabel(self.centralwidget)
        self.IdLabel.setGeometry(QtCore.QRect(120, 250, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.IdLabel.setFont(font)
        self.IdLabel.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.IdLabel.setText("")
        self.IdLabel.setObjectName("IdLabel")
        self.locationLabel = QtWidgets.QLabel(self.centralwidget)
        self.locationLabel.setGeometry(QtCore.QRect(120, 350, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.locationLabel.setFont(font)
        self.locationLabel.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.locationLabel.setText("")
        self.locationLabel.setObjectName("locationLabel")
        self.adminIdLabel = QtWidgets.QLabel(self.centralwidget)
        self.adminIdLabel.setGeometry(QtCore.QRect(120, 440, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adminIdLabel.setFont(font)
        self.adminIdLabel.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.adminIdLabel.setText("")
        self.adminIdLabel.setObjectName("adminIdLabel")
        self.totalFloorsLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalFloorsLabel.setGeometry(QtCore.QRect(120, 540, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalFloorsLabel.setFont(font)
        self.totalFloorsLabel.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.totalFloorsLabel.setText("")
        self.totalFloorsLabel.setObjectName("totalFloorsLabel")
        self.totalRoomsLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalRoomsLabel.setGeometry(QtCore.QRect(750, 250, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalRoomsLabel.setFont(font)
        self.totalRoomsLabel.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.totalRoomsLabel.setText("")
        self.totalRoomsLabel.setObjectName("totalRoomsLabel")
        self.totalBedsLabel = QtWidgets.QLabel(self.centralwidget)
        self.totalBedsLabel.setGeometry(QtCore.QRect(750, 350, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalBedsLabel.setFont(font)
        self.totalBedsLabel.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.totalBedsLabel.setText("")
        self.totalBedsLabel.setObjectName("totalBedsLabel")
        self.floorsGenderLabel = QtWidgets.QLabel(self.centralwidget)
        self.floorsGenderLabel.setGeometry(QtCore.QRect(750, 450, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.floorsGenderLabel.setFont(font)
        self.floorsGenderLabel.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.floorsGenderLabel.setText("")
        self.floorsGenderLabel.setObjectName("floorsGenderLabel")
        deleteBuilding.setCentralWidget(self.centralwidget)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1181, 581))
        self.label.setStyleSheet("background-image: url(background.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.lower()

        self.statusbar = QtWidgets.QStatusBar(deleteBuilding)
        self.statusbar.setObjectName("statusbar")
        deleteBuilding.setStatusBar(self.statusbar)

        self.retranslateUi(deleteBuilding)
        QtCore.QMetaObject.connectSlotsByName(deleteBuilding)

    def retranslateUi(self, deleteBuilding):
        _translate = QtCore.QCoreApplication.translate
        deleteBuilding.setWindowTitle(_translate("deleteBuilding", "deleteBuilding"))
        self.showPushButton.setText(_translate("deleteBuilding", "Show "))
        self.ageLabel_3.setText(_translate("deleteBuilding", "Total Rooms"))
        self.ageLabel_4.setText(_translate("deleteBuilding", "Total Beds"))
        self.idLabel.setText(_translate("deleteBuilding", "Id"))
        self.ageLabel.setText(_translate("deleteBuilding", "Location"))
        self.nameLabel_2.setText(_translate("deleteBuilding", "Admin Id"))
        self.deleteButton.setText(_translate("deleteBuilding", "Delete"))
        self.adminDashboardLabel.setText(_translate("deleteBuilding", "Delete Building"))
        self.ageLabel_2.setText(_translate("deleteBuilding", "Total Floors"))
        self.ageLabel_5.setText(_translate("deleteBuilding", "Floors Gender"))


# main
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteBuilding = QtWidgets.QMainWindow()
    ui = Ui_deleteBuilding()
    ui.setupUi(deleteBuilding)
    deleteBuilding.show()
    sys.exit(app.exec_())
