# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifyBuilding.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Admin_Dashboardnew as AD
from tkinter import messagebox
from main import main_control
from login import gui as G
import Buildings_Managmentnew as BM



class Ui_modifyBuilding(object):


    def logOut(self,modifyBuilding):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()
        modifyBuilding.close()


    def back(self,modifyBuilding):
        self.Buildings_Managment = QtWidgets.QMainWindow()
        self.ui = BM.Ui_Buildings_Managment()
        self.ui.setupUi(self.Buildings_Managment)
        self.Buildings_Managment.show()
        modifyBuilding.close()

    #get building info from control
    def editBuilding(self):

        mc = main_control()
        result = mc.getGuiMsgsControl()
        if (self.idLineEdit.text() == ''):
            messagebox.showwarning('Warning', str(result[6]))
            return
        emptuple = (self.locationLineEdit.text(), int(self.totalFloorsLineEdit.text()), int(self.idLineEdit.text()))
        isacceptable = mc.editBuildingControl(emptuple)
        if str(isacceptable).lower() == "none":
            messagebox.showinfo('information', str(result[7]))
            # self.clearLineEdits()
            self.showBuilding()

        else:
            ermsg2 = str(result[5])
            ermsg1 = str(isacceptable)
            ermsg = ermsg2 + " " + ermsg1
            messagebox.showerror('Error', ermsg)

    # clear text boxes
    def clearLineEdits(self):
        self.locationLineEdit.clear()
        self.totalFloorsLineEdit.clear()



    # collect building info and send to CONTROL to get info from db
    def showBuilding(self):
        _translate = QtCore.QCoreApplication.translate
        self.clearLineEdits()

        mc = main_control()
        result = mc.getGuiMsgsControl()
        if (self.idLineEdit.text() == ''):
            messagebox.showwarning('Warning', str(result[6]))
            return
        result = mc.getBuildingInfoControl(int(self.idLineEdit.text()))

        if (not result):
            result = mc.getGuiMsgsControl()
            messagebox.showerror('Error', result[8])
            return
        self.locationLineEdit.insert(_translate("modifyEmployee", str(result[0][1])))
        self.totalFloorsLineEdit.insert(_translate("modifyEmployee", str(result[0][2])))
        return

    def setupUi(self, modifyBuilding):
        modifyBuilding.setObjectName("modifyBuilding")
        modifyBuilding.resize(1200, 600)
        modifyBuilding.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(modifyBuilding)
        self.centralwidget.setObjectName("centralwidget")

        self.idLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_5.setGeometry(QtCore.QRect(210, 295, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_5.setFont(font)
        self.idLabel_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(location-pin.png);")
        self.idLabel_5.setText("")
        self.idLabel_5.setObjectName("idLabel_5")
        self.showNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.showNameLabel.setGeometry(QtCore.QRect(120, 255, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showNameLabel.setFont(font)
        self.showNameLabel.setStyleSheet("color: rgb(122, 122, 122);")
        self.showNameLabel.setObjectName("showNameLabel")
        self.idLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_4.setGeometry(QtCore.QRect(220, 395, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_4.setFont(font)
        self.idLabel_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_4.setText("")
        self.idLabel_4.setObjectName("idLabel_4")
        self.idLabel_6 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_6.setGeometry(QtCore.QRect(230, 485, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_6.setFont(font)
        self.idLabel_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(plan.png);")
        self.idLabel_6.setText("")
        self.idLabel_6.setObjectName("idLabel_6")
        self.ageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel.setGeometry(QtCore.QRect(120, 295, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.showPushButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.showBuilding())
        self.showPushButton.setGeometry(QtCore.QRect(280, 190, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.showPushButton.setFont(font)
        self.showPushButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(140,140,140);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}")
        self.showPushButton.setObjectName("showPushButton")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 25, 71, 61))
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.totalFloorsLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.totalFloorsLineEdit.setGeometry(QtCore.QRect(750, 245, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalFloorsLineEdit.setFont(font)
        self.totalFloorsLineEdit.setStyleSheet("\n"
"color: rgb(170, 0, 0);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"")
        self.totalFloorsLineEdit.setObjectName("totalFloorsLineEdit")

        self.locationLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.locationLineEdit.setGeometry(QtCore.QRect(120, 345, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.locationLineEdit.setFont(font)
        self.locationLineEdit.setStyleSheet("color: rgb(170, 0, 0);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"")
        self.locationLineEdit.setText("")
        self.locationLineEdit.setObjectName("locationLineEdit")
        self.ageLabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_4.setGeometry(QtCore.QRect(750, 295, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_4.setFont(font)
        self.ageLabel_4.setObjectName("ageLabel_4")

        self.nameLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel_2.setGeometry(QtCore.QRect(120, 395, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.nameLabel_2.setFont(font)
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.showResidentInfoPushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.logOut(modifyBuilding))
        self.showResidentInfoPushButton_2.setGeometry(QtCore.QRect(1090, 25, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.showResidentInfoPushButton_2.setFont(font)
        self.showResidentInfoPushButton_2.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(logout.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.showResidentInfoPushButton_2.setText("")
        self.showResidentInfoPushButton_2.setObjectName("showResidentInfoPushButton_2")
        self.idLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idLineEdit.setGeometry(QtCore.QRect(120, 245, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLineEdit.setFont(font)
        self.idLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);\n"
"")
        self.idLineEdit.setText("")
        self.idLineEdit.setObjectName("idLineEdit")
        self.ageLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_2.setGeometry(QtCore.QRect(120, 485, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_2.setFont(font)
        self.ageLabel_2.setObjectName("ageLabel_2")
        self.showResidentInfoPushButton_3 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.back(modifyBuilding))
        self.showResidentInfoPushButton_3.setGeometry(QtCore.QRect(970, 25, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.showResidentInfoPushButton_3.setFont(font)
        self.showResidentInfoPushButton_3.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.showResidentInfoPushButton_3.setText("")
        self.showResidentInfoPushButton_3.setObjectName("showResidentInfoPushButton_3")
        self.idLabel_7 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_7.setGeometry(QtCore.QRect(850, 295, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_7.setFont(font)
        self.idLabel_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(beds.png);")
        self.idLabel_7.setText("")
        self.idLabel_7.setObjectName("idLabel_7")
        self.idLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_2.setGeometry(QtCore.QRect(430, 95, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_2.setFont(font)
        self.idLabel_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(home.png);")
        self.idLabel_2.setText("")
        self.idLabel_2.setObjectName("idLabel_2")
        self.idLabel_9 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_9.setGeometry(QtCore.QRect(880, 195, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_9.setFont(font)
        self.idLabel_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(living-room.png);")
        self.idLabel_9.setText("")
        self.idLabel_9.setObjectName("idLabel_9")
        self.adminDashboardLabel = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel.setGeometry(QtCore.QRect(25, 95, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel.setFont(font)
        self.adminDashboardLabel.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel.setObjectName("adminDashboardLabel")
#         self.totalRoomsLineEdit = QtWidgets.QLineEdit(self.centralwidget)
#         self.totalRoomsLineEdit.setGeometry(QtCore.QRect(750, 245, 241, 31))
#         font = QtGui.QFont()
#         font.setPointSize(12)
#         self.totalRoomsLineEdit.setFont(font)
#         self.totalRoomsLineEdit.setStyleSheet("\n"
# "color: rgb(170, 0, 0);\n"
# "border-radius:0px;\n"
# "border-bottom: 3px solid #3c79b5;\n"
# "padding-bottom:0px;\n"
# "")
#         self.totalRoomsLineEdit.setObjectName("totalRoomsLineEdit")
        self.idLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_3.setGeometry(QtCore.QRect(180, 195, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_3.setFont(font)
        self.idLabel_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(driver-license.png);")
        self.idLabel_3.setText("")
        self.idLabel_3.setObjectName("idLabel_3")
        self.ageLabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_3.setGeometry(QtCore.QRect(750, 195, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_3.setFont(font)
        self.ageLabel_3.setObjectName("ageLabel_3")
        self.ageLabel_5 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_5.setGeometry(QtCore.QRect(750, 395, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_5.setFont(font)
        self.ageLabel_5.setObjectName("ageLabel_5")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.editBuilding())
        self.addButton.setGeometry(QtCore.QRect(700, 505, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}")
        self.addButton.setObjectName("addButton")
        self.idLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.idLabel_8.setGeometry(QtCore.QRect(880, 395, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.idLabel_8.setFont(font)
        self.idLabel_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"image: url(gender-fluid.png);")
        self.idLabel_8.setText("")
        self.idLabel_8.setObjectName("idLabel_8")
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setGeometry(QtCore.QRect(120, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.idLabel.setFont(font)
        self.idLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.idLabel.setObjectName("idLabel")
        modifyBuilding.setCentralWidget(self.centralwidget)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1181, 581))
        self.label.setStyleSheet("background-image: url(background.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.lower()

        self.statusbar = QtWidgets.QStatusBar(modifyBuilding)
        self.statusbar.setObjectName("statusbar")
        modifyBuilding.setStatusBar(self.statusbar)

        self.retranslateUi(modifyBuilding)
        QtCore.QMetaObject.connectSlotsByName(modifyBuilding)

    def retranslateUi(self, modifyBuilding):
        _translate = QtCore.QCoreApplication.translate
        modifyBuilding.setWindowTitle(_translate("modifyBuilding", "modifyBuilding"))
        self.showNameLabel.setText(_translate("modifyBuilding", "xx"))
        self.ageLabel.setText(_translate("modifyBuilding", "Location"))
        self.showPushButton.setText(_translate("modifyBuilding", "Show "))
        self.adminDashboardLabel.setText(_translate("modifyBuilding", "Modify Building"))
        self.ageLabel_3.setText(_translate("modifyBuilding", "Total Floors"))
        self.addButton.setText(_translate("modifyBuilding", "Modify"))
        self.idLabel.setText(_translate("modifyBuilding", "Id"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modifyBuilding = QtWidgets.QMainWindow()
    ui = Ui_modifyBuilding()
    ui.setupUi(modifyBuilding)
    modifyBuilding.show()
    sys.exit(app.exec_())
