# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updateRoomStatus.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from login import gui as G
import floorAdmin_Dashboardnew as FD


def close():
    updateRoomStatus.close()
    pass

class Ui_updateRoomStatus(object):

    def logOut(self):
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = G.Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()
        close()

    def back(self):
                self.floorAdmin_Dashboard = QtWidgets.QMainWindow()
                self.ui = FD.Ui_floorAdmin_Dashboard()
                self.ui.setupUi(self.floorAdmin_Dashboard)
                self.floorAdmin_Dashboard.show()
                close()
    def update(self):
        return

    def setupUi(self, updateRoomStatus):
        updateRoomStatus.setObjectName("updateRoomStatus")
        updateRoomStatus.resize(1200, 600)
        updateRoomStatus.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.centralwidget = QtWidgets.QWidget(updateRoomStatus)
        self.centralwidget.setObjectName("centralwidget")
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setGeometry(QtCore.QRect(220, 225, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.idLabel.setFont(font)
        self.idLabel.setObjectName("idLabel")
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.idLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.idLineEdit.setGeometry(QtCore.QRect(220, 280, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idLineEdit.setFont(font)
        self.idLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.idLineEdit.setObjectName("idLineEdit")
        self.ageLabel_8 = QtWidgets.QLabel(self.centralwidget)
        self.ageLabel_8.setGeometry(QtCore.QRect(770, 220, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI Semilight")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ageLabel_8.setFont(font)
        self.ageLabel_8.setObjectName("ageLabel_8")
        self.dateOfBirthLabel = QtWidgets.QLabel(self.centralwidget)
        self.dateOfBirthLabel.setGeometry(QtCore.QRect(130, 530, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateOfBirthLabel.setFont(font)
        self.dateOfBirthLabel.setStyleSheet("color: rgb(122, 122, 122);")
        self.dateOfBirthLabel.setText("")
        self.dateOfBirthLabel.setObjectName("dateOfBirthLabel")
        self.newStatusLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.newStatusLineEdit.setGeometry(QtCore.QRect(770, 270, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.newStatusLineEdit.setFont(font)
        self.newStatusLineEdit.setStyleSheet("color: rgb(122, 122, 122);\n"
"border-radius:0px;\n"
"border-bottom: 3px solid #3c79b5;\n"
"padding-bottom:0px;\n"
"color: rgb(170, 0, 0);")
        self.newStatusLineEdit.setObjectName("newStatusLineEdit")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.updateButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.update())
        self.updateButton.setGeometry(QtCore.QRect(430, 490, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.updateButton.setFont(font)
        self.updateButton.setStyleSheet("QPushButton {\n"
                                     "background-color: rgb(0,100,150);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}\n"
                                     "QPushButton:hover\n"
                                     "{\n"
                                     "background-color: rgb(170,0,0);\n"
                                     "border-radius: 13px;\n"
                                     "color: white;\n"
                                     "}"
)
        self.updateButton.setObjectName("updateButton")
        self.adminDashboardLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.adminDashboardLabel_2.setGeometry(QtCore.QRect(50, 110, 511, 71))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.adminDashboardLabel_2.setFont(font)
        self.adminDashboardLabel_2.setStyleSheet("color: rgb(41, 84, 125);\n"
"text-align: left;\n"
"")
        self.adminDashboardLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.adminDashboardLabel_2.setObjectName("adminDashboardLabel_2")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(20, 20, 71, 61))
        self.logoLabel.setStyleSheet("background-image: url(imageedit_2_5347177992.jpg);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.logOutButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.logOut())
        self.logOutButton.setGeometry(QtCore.QRect(1090, 20, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.logOutButton.setFont(font)
        self.logOutButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(logout (2).png);\n"

"color: rgb(255, 255, 255);\n"
"text-align: left;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.logOutButton.setText("")
        self.logOutButton.setObjectName("logOutButton")
        self.backButton = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.back())
        self.backButton.setGeometry(QtCore.QRect(970, 20, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"image: url(left-arrow-in-circular-button.png);\n"
"color: rgb(255, 255, 255);\n"
"text-align: center;\n"
"border-radius:6px;\n"
"padding: 10px; \n"
"")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        updateRoomStatus.setCentralWidget(self.centralwidget)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1181, 581))
        self.label.setStyleSheet("background-image: url(background.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.lower()

        self.statusbar = QtWidgets.QStatusBar(updateRoomStatus)
        self.statusbar.setObjectName("statusbar")
        updateRoomStatus.setStatusBar(self.statusbar)

        self.retranslateUi(updateRoomStatus)
        QtCore.QMetaObject.connectSlotsByName(updateRoomStatus)

    def retranslateUi(self, updateRoomStatus):
        _translate = QtCore.QCoreApplication.translate
        updateRoomStatus.setWindowTitle(_translate("updateRoomStatus", "updateRoomStatus"))
        self.idLabel.setText(_translate("updateRoomStatus", "Enter Bed Id"))
        self.ageLabel_8.setText(_translate("updateRoomStatus", "Enter New Status"))
        self.updateButton.setText(_translate("updateRoomStatus", "Update"))
        self.adminDashboardLabel_2.setText(_translate("updateRoomStatus", "Update Room Status"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    updateRoomStatus = QtWidgets.QMainWindow()
    ui = Ui_updateRoomStatus()
    ui.setupUi(updateRoomStatus)
    updateRoomStatus.show()
    sys.exit(app.exec_())
